Planning-Inspectorate/infrastructure-environments

pipelines/infra-ci.yml
- Use the wrapper_ci template instead of defining a load of steps ourselves
=> Use wrapper template for CI pipeline

app/modules/node-app-service/README.md, app/modules/node-app-service/main.tf, app/modules/node-app-service/variables.tf, app/stacks/appeals-service/README.md, app/stacks/appeals-service/app-service.tf, app/stacks/appeals-service/subnet.tf, app/stacks/appeals-service/terragrunt.hcl, app/stacks/appeals-service/variables.tf, app/stacks/applications-service/README.md, app/stacks/applications-service/app-service.tf, app/stacks/applications-service/subnet.tf, app/stacks/applications-service/terragrunt.hcl, app/stacks/applications-service/variables.tf, app/stacks/common/README.md, app/stacks/common/network.tf, app/stacks/common/outputs.tf
This PR separates out the private endpoint subnets for each app stack so that security filtering or routing may be applied more easily if desired later.
- Remove subnet definitions from the common VNET file.
- Add outputs for VNET name and resource group name to the common stack.
- Add individual subnet files to each app stack.
- Update the the app service module has correct inputs for the ingress and egress subnets.
- Update inputs and mock values for Terragrunt.
At the time of writing there is throttling in effect for Cosmos DB which will affect deployment to the Dev environment. This branch has already been successfully deployed (manually) to the Test and Production environments.
=> Separate private endpoint subnets per app stack

app/stacks/appeals-service/README.md, app/stacks/appeals-service/subnet.tf, app/stacks/appeals-service/terragrunt.hcl, app/stacks/appeals-service/variables.tf, app/stacks/applications-service/README.md, app/stacks/applications-service/subnet.tf, app/stacks/applications-service/terragrunt.hcl, app/stacks/applications-service/variables.tf, app/stacks/common/README.md, app/stacks/common/address-space.tf, app/stacks/common/network.tf, app/stacks/common/outputs.tf, app/stacks/common/variables.tf, config/variables/dev.hcl, config/variables/prod.hcl, config/variables/test.hcl, pipelines/infra-ci.yml
- Allows the common VNET address space to be specified individually for each environment.
- Dynamically creates subnet prefixes for each subnet based on the given VNET address space.
- Fix CI pipeline to work with common pipeline template updates.
=> Assign VNET address space per environment and dynamically create subnet prefixes

app/stacks/applications-service/README.md, app/stacks/applications-service/data.tf, app/stacks/applications-service/terragrunt.hcl, app/stacks/applications-service/variables.tf, app/stacks/applications-service/vpn-gateway.tf, app/stacks/common/README.md, app/stacks/common/address-space.tf, app/stacks/common/data.tf, app/stacks/common/key-vault.tf, app/stacks/common/locals.tf, app/stacks/common/network.tf, app/stacks/common/outputs.tf, app/stacks/common/vpn-gateway.tf, config/variables/dev.hcl, config/variables/prod.hcl, config/variables/test.hcl
- Adds a virtual network gateway to the common stack with AppGateway subnet.
- Adds a local network gateway and site-to-site VPN connection to the Applications Service stack.
- Integrates with the common key vault to retrieve the shared key for VPN connection encryption.
=> Add virtual network gateway resources with key vault integration for shared key

app/modules/node-app-service/README.md, app/modules/node-app-service/data.tf, app/modules/node-app-service/main.tf, app/modules/node-app-service/variables.tf, app/stacks/applications-service/README.md, app/stacks/applications-service/app-service.tf, app/stacks/applications-service/terragrunt.hcl, app/stacks/applications-service/variables.tf, app/stacks/common/README.md, app/stacks/common/locals.tf, app/stacks/common/outputs.tf
- Added `azurerm_key_vault_access_policy` resource so App Services can access Key Vault
- Fixed secret references as they were missing closing bracket
=> Add key vault policy for app services and fix secret references

app/modules/node-app-service/main.tf, app/stacks/applications-service/README.md, app/stacks/applications-service/outputs.tf, app/stacks/front-door/front-door.tf, app/stacks/front-door/locals.tf, app/stacks/front-door/region.tf, app/stacks/front-door/terragrunt.hcl, app/stacks/front-door/variables.tf, pipelines/infra-cd.yml
- Deploys a Front Door instance per environment.
- Includes a default frontend `*.azurefd.net/*` with routing rule to the National Infrastructure frontend app service.
- Adds a dynamic access restriction to frontend web apps to ensure only connections from Front Door are accepted.
- _N.B._ Custom domain frontends and routing rules to be added in a later PR (semi-dependent on SSL certificates).
- _N.B._ Front Door may move to the tooling subscription to act as a shared resource if desirable.
=> Initial Front Door deployment with frontend app service restrictions

app/stacks/appeals-service/README.md, app/stacks/appeals-service/outputs.tf, app/stacks/front-door/front-door.tf, app/stacks/front-door/locals.tf, app/stacks/front-door/terragrunt.hcl, app/stacks/front-door/variables.tf, config/variables/dev.hcl, config/variables/prod.hcl, config/variables/test.hcl
- Added custom domain names for Dev, Pre-Prod, and Production.
- Changed service name for the Front Door stack to common.
- Deployed to test and confirmed working subsequent to public DNS records being registered.
=> Add custom domains for all environments

app/stacks/front-door/front-door.tf, app/stacks/front-door/waf-policy.tf
- Adds a basic Web Application Firewall policy to all Front Door frontends.
- Includes all [Default Rule Set](https://docs.microsoft.com/en-us/azure/web-application-firewall/afds/waf-front-door-drs?tabs=drs20#default-rule-sets) managed policy settings. Does not include [Bot Rules (Preview)](https://docs.microsoft.com/en-us/azure/web-application-firewall/afds/waf-front-door-drs?tabs=drs20#bot-rules).
=> Add WAF to Front Door

config/variables/dev.hcl
- Changes the node environment variable for Dev to `development` to prevent the Applications service API App Service database connection from using localhost.
=> Change node environment variable for Dev

app/stacks/global/front-door/terragrunt.hcl
- Temporary solution to work around Cosmos DB outages in UK South affecting the deployment of the Appeals service stack. Allows Front Door to be deployed just for the Applications service to facilitate environment deployments to Test and Prod.
=> Remove Front Door dependency on Appeals service stack

config/variables/stacks/applications-service/prod.hcl, config/variables/stacks/applications-service/test.hcl
- Adds the remote virtual network gateway public IP addresses and address space.
- Allows the Applications service for Test and Prod environments to establish connectivity to the respective NI SQL database.
=> Add remote gateway IPs and address spaces for Applications connectivity

app/components/appeals-app-services/README.md, app/components/appeals-app-services/locals.tf, app/components/appeals-app-services/variables.tf, app/components/networking/README.md, app/components/networking/network.tf, app/components/networking/outputs.tf, app/components/networking/variables.tf, app/stacks/uk-south/appeals-service/README.md, app/stacks/uk-south/appeals-service/app-service.tf, app/stacks/uk-south/appeals-service/cosmosdb.tf, app/stacks/uk-south/appeals-service/terragrunt.hcl, app/stacks/uk-south/appeals-service/variables.tf, app/stacks/uk-south/common/README.md, app/stacks/uk-south/common/networking.tf, app/stacks/uk-south/common/variables.tf, app/stacks/uk-west/appeals-service/README.md, app/stacks/uk-west/appeals-service/app-service.tf, app/stacks/uk-west/appeals-service/cosmosdb.tf, app/stacks/uk-west/appeals-service/outputs.tf, app/stacks/uk-west/appeals-service/storage-account.tf, app/stacks/uk-west/appeals-service/variables.tf, app/stacks/uk-west/common/README.md, app/stacks/uk-west/common/locals.tf, app/stacks/uk-west/common/networking.tf, app/stacks/uk-west/common/variables.tf, config/variables/dev.hcl, config/variables/stacks/appeals-service/dev.hcl, config/variables/stacks/appeals-service/prod.hcl, config/variables/stacks/appeals-service/test.hcl, pipelines/infra-cd.yml
- Add app settings for remaining Appeals Service applications
- Changes some settings on CosmosDB the frontend needs
- Removes private endpoint on CosmosDB when in the Dev environment to allow connecting to the database via Compass
- Add region tag to deployments
=> Add additional app settings for frontend, documents api, and pdf api

config/variables/prod.hcl
- Update the Applications URL in the production environment to its established go-live URL.
- Remove redundant comments.
=> Add production URL for the Applications service

pipelines/infra-ci.yml
- Since we introduced the components folder and the concept of regions, the paths to some modules in the TFLint build step were broken
=> Fix paths to terraform modules in CI pipeline

app/stacks/uk-south/back-office/README.md, app/stacks/uk-south/back-office/database.tf, app/stacks/uk-south/back-office/variables.tf, app/stacks/uk-west/back-office/README.md, app/stacks/uk-west/back-office/database.tf, app/stacks/uk-west/back-office/locals.tf, app/stacks/uk-west/back-office/variables.tf, config/variables/stacks/back-office/dev.hcl, config/variables/stacks/back-office/prod.hcl, config/variables/stacks/back-office/test.hcl
- Add an AAD administrator assignment to the Back Office SQL server in addition to the local SQL administrator.
- Add a short-term retention policy, configurable per environment, to the Back Office database.
- Remove URL encoding for the database connection string to fix authentication.
=> SQL server AAD admin and short-term database retention policy

app/stacks/uk-west/back-office/database.tf
- Secret values were not updating because they were populated from the random id instead of the actual server values
=> Fix values for username and password that were not updating

app/components/appeals-app-services/README.md, app/components/appeals-app-services/service-bus.tf
- Appeals no longer talks to an SQL database as this is part of the back office project. So there is no need to keep the queue as the function will be removed.
=> Remove unused Service Bus queue

app/components/appeals-app-services/README.md, app/components/appeals-app-services/locals.tf
- Split the Horizon service bus connection string to pass in only the shared access key to the `HORIZON_HAS_PUBLISHER_PASSWORD` environment variable.
=> Fix Horizon publisher environment variable

app/modules/node-app-service/README.md, app/modules/node-app-service/main.tf, config/variables/stacks/back-office/dev.hcl, config/variables/stacks/back-office/test.hcl, pipelines/infra-cd.yml, pipelines/infra-ci.yml
- Use a separate App Registration per environment for the Back Office Authentication
- Fixes a dependency issue in the App Service module where the VNet integration was not provisioned in the correct order
- Allow staging slots ability to read from Key Vault
- Update pipeline to remove skipApply as this is now done in the templates
=> Separate App Registration per environment for Back Office auth

app/modules/node-app-service/locals.tf, app/modules/node-app-service/main.tf
Removing the hack to make staging slots point at other staging slots. Reason for this is that when you do the slot swap, it also swaps the values of the app settings.
=> Remove staging slot settings and use values from production slot

app/stacks/global/front-door/waf-policy.tf
- Add a web application firewall rule exclusion for the RFI ruleset which was preventing request body posts for applicant website.
- Successfully deployed and tested in the dev environment to fix BOAS-153.
=> Add WAF exclusion for applicant website

app/stacks/global/front-door/front-door.tf
- Add a dependency on applying WAF policy before linking Front Door rules engine to routing rules.
=> Add dependency on waf policy for rule engine linking

app/components/applications-app-services/README.md, app/components/applications-app-services/locals.tf
- Adds `FILE_UPLOADS_PATH` environment variable for the Applications App Service container, which defines the path the app should use as temporary storage for uploading files
=> chore(applications-app-service): add path env var

app/components/appeals-app-services/README.md, app/components/appeals-app-services/iam.tf, app/components/appeals-app-services/locals.tf, app/stacks/uk-south/appeals-service/README.md, app/stacks/uk-south/appeals-service/app-service-config.tf, app/stacks/uk-south/appeals-service/data.tf, app/stacks/uk-west/appeals-service/README.md, app/stacks/uk-west/appeals-service/app-service-config.tf, app/stacks/uk-west/appeals-service/data.tf
- Grant RBAC permissions to the documents API for accessing App Configuration stores.
- Add a private endpoint for App Configuration stores to facilitate private access.
=> App Service private access to App Configuration and Key Vault

app/stacks/uk-south/back-office/README.md, app/stacks/uk-south/back-office/app-service.tf, app/stacks/uk-south/back-office/service-bus.tf, app/stacks/uk-south/back-office/variables.tf, app/stacks/uk-west/back-office/README.md, app/stacks/uk-west/back-office/service-bus.tf, app/stacks/uk-west/back-office/variables.tf, config/variables/stacks/back-office/dev.hcl, config/variables/stacks/back-office/prod.hcl, config/variables/stacks/back-office/test.hcl
- Sets the default Service Bus SKU to `Standard` to save costs. Retains the `Premium` SKU for production to support high-availability and disaster recovery scenarios.
=> Conditional Service Bus SKU per environment

app/stacks/uk-south/applications-service/vpn-gateway.tf, app/stacks/uk-south/back-office/terragrunt.hcl
- Move the VPN gateway resources to the common resource group.
- Fix mock value for storage account ID.
=> Failover deployment fixes

config/variables/stacks/applications-service/prod.hcl
Default Applications document library functionality to be on as it is now active in production.
=> chore(applications): default document library feature flag on

app/components/applications-app-services/README.md, app/components/applications-app-services/function-app.tf
- adds filter to the `applications-nsip-project-subscription` so that we only receive messages with `type` of `Publish` from Back Office Service Bus
=> feat(applications-service): add filter to applications-nsip-project subscription

app/components/appeals-app-services/locals.tf
set 'USE_SECURE_SESSION_COOKIES' to true
Setting to true will partially address the concerns in: [[AS-5886] - PINS Jira (atlassian.net)](https://pins-ds.atlassian.net/browse/AS-5886)
Will also tangentially fix: [[AS-5898] - PINS Jira (atlassian.net)](https://pins-ds.atlassian.net/browse/AS-5898) as trust proxy setting is driven off this and will pick up the domain/subdomain from azure front door
=> fix(appeals-service): set secure cookie true

app/components/appeals-app-services/README.md, app/components/appeals-app-services/locals.tf, app/components/appeals-app-services/variables.tf, app/stacks/uk-south/appeals-service/README.md, app/stacks/uk-south/appeals-service/app-service.tf, app/stacks/uk-south/appeals-service/variables.tf, app/stacks/uk-west/appeals-service/README.md, app/stacks/uk-west/appeals-service/app-service.tf, app/stacks/uk-west/appeals-service/variables.tf, config/variables/stacks/appeals-service/dev.hcl, config/variables/stacks/appeals-service/prod.hcl, config/variables/stacks/appeals-service/test.hcl
Add ALLOW_TESTING_OVERRIDES to allow custom testing code to be used in non prod environment
=> feat(appeals-service): add env variable ALLOW_TESTING_OVERRIDES

app/components/back-office-app-services/locals.tf
Returns the storage container name to the web app settings for appeals
=> feat(bo/appeals): env setting for blob container

app/stacks/uk-west/back-office/storage-account.tf
Adds the new appeals wfe domain to storage cors settings.
=> fix(appeals/web): document storage cors

app/components/back-office-app-services/iam.tf
Adds permissions for:
- appeal case officers -> write to blob storage
- appeal inspectors -> write to blob storage
- appeals api -> write to service bus
=> fix(appeals/web): document storage permissions

app/components/back-office-app-services/deadline-submissions-function/function-app.tf
Azure imposes a 60 character limit on the name of an `azurerm_linux_function_app` which uses both of these properties.
=> Shorten app_name and service_name on deadline subs function

app/stacks/global/front-door/waf-policy.tf
Add exception to WAF for back office HTML on Post.
This should allow html links to be posted as part of the updates generation on form field - backOfficeProjectUpdateContent.
=> Add WAF exclusion for BO updates: XSS Filter - Category 5

config/variables/stacks/back-office/dev.hcl, config/variables/stacks/back-office/prod.hcl, config/variables/stacks/back-office/test.hcl
Back Office: Use (dev) and (test) AD groups for access to the corresponding environments.
=> fix(back-office): ad groups

app/stacks/global/front-door/waf-policy.tf
Replace the existing override WAF rule with a ruleset level exclusion for the backOfficeProjectUpdateContent post.
=> fxeat(applications-fo): Disable WAF rules for backOfficeProjectUpdate content

app/stacks/uk-south/applications-service/README.md, app/stacks/uk-south/applications-service/database.tf, app/stacks/uk-south/applications-service/terragrunt.hcl, app/stacks/uk-south/applications-service/variables.tf, app/stacks/uk-west/applications-service/README.md, app/stacks/uk-west/applications-service/outputs.tf
ASB-1949
Adds failover group for Applications front office Azure SQL server and database.
Set to manual failover until a disaster recovery strategy is defined
=> feat(applications-service): add failover group for applications db

app/components/applications-app-services/README.md, app/components/applications-app-services/function-app.tf
Add subscription rule for `"applications-nsip-exam-timetable"` subscription, so that subscriber function will only be invoked when incoming message has `type` header set to `Publish` (otherwise function will also invoke on other types, such as `Unpublish`)
=> fix(applications-service): add subscription rule for nsip-exam-timetable

app/components/back-office-app-services/doc-scanning.tf, app/components/back-office-app-services/document-check-function/function-app.tf, app/components/back-office-app-services/document-check-function/variables.tf
Microsoft Defender will now handle malware scanning for this account.
Set an environment variable on the document check function to disable it for the storage account now being handled by Microsoft Defender.
=> Pass back_office_documents to document-check as an excluded account

app/components/appeals-app-services/locals.tf, app/stacks/uk-south/appeals-service/README.md, app/stacks/uk-south/appeals-service/database.tf, app/stacks/uk-south/appeals-service/locals.tf, app/stacks/uk-south/appeals-service/secrets.tf, app/stacks/uk-south/appeals-service/terragrunt.hcl, app/stacks/uk-south/appeals-service/variables.tf, app/stacks/uk-west/appeals-service/README.md, app/stacks/uk-west/appeals-service/database.tf, app/stacks/uk-west/appeals-service/locals.tf, app/stacks/uk-west/appeals-service/outputs.tf, app/stacks/uk-west/appeals-service/secrets.tf
Looks as if  the definition of the failover group is enough to create the db in uk south, as such have removed the redundant second db in uk south
Have also reused the admin login details from ukw sql server in uks
Have added an application user to used as a connection string in place of admin login to reduce permissions that the apps connecting to the db have. These will have to be manually added as logins/user to sql server after creation
=> feat(appeals-fo): remove redundant sql db and reuse ukw login for uks

app/stacks/global/front-door/waf-policy.tf
[Issue ticket number and link](https://pins-ds.atlassian.net/browse/ASB-2070)
https://pins-ds.atlassian.net/browse/ASB-2059
Add WAF exclusions for applications session.sid which is blocking users for hex encoding however there are often hex chars 
in the session sid which is blocking quite a few users from accessing the site.
Also exclude all blocks for submitting comments, we currently have a service worker to capture this data, however where users have disabled javascript they are unable to get past the WAF block.  This is only for the 'comment' past fields in the applications service registrations and submission forms.
1) For the comment issue, turn off javascript and post comment value:
s:gXjqsCkvGr9FQ9JlxsMAaoD9ufqJ7SfX.dV0X8a5koWbp2HIUEx7v5sBC50/JTg1aFU5lCebDldo
2) For the session …
=> fix: Add waf exclusions for false positive Applications blocks

app/stacks/uk-south/back-office/database.tf, app/stacks/uk-west/back-office/database.tf
This seems to be preventing the storage account from being created.
* Comment out network_rules block from new storage accounts in back-office
This seems to be preventing the storage account from being created.
=> Comment out network_rules block from new storage accounts in back-office

app/stacks/global/front-door/front-door.tf
There is an error during deployment about the name of this WAF rule. This change makes the format inline with the other rule names.
* Rename "Book Reference File Robots Tag" to remove spaces and uppercase
There is an error during deployment about the name of this WAF rule.
This change makes the format inline with the other rule names.
=> Rename "Book Reference File Robots Tag" to remove spaces and uppercase

app/components/back-office-app-services/applications-migration-function/function-app.tf, app/components/back-office-app-services/applications-migration-function/variables.tf, app/components/back-office-app-services/func-applications-migration.tf
Add `KEY_VAULT_ENABLED` feature flag to back office migration function app
value to be passed to [addAuthHeadersForBackend](https://github.com/Planning-Inspectorate/back-office/blob/3fffc7d4643742fcc7174d88bb5124a1475d6555/apps/functions/applications-migration/common/back-office-api-client.js#L27) function to allow api key requirement to be disabled when running function locally
=> chore: add key vault flag for back office functions

app/stacks/global/front-door/waf-policy.tf
Current overridden rules were missing a property that ensures that they stay enabled when overridden. Overriding them without this property defaults the firewall rule to be disabled as per the [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor_firewall_policy#:~:text=The%20rule%20block%20supports%20the%20following%3A).
=> enable overridden waf rules

config/variables/stacks/appeals-service/dev.hcl, config/variables/stacks/appeals-service/prod.hcl, config/variables/stacks/appeals-service/test.hcl
AAPD-1728
Adds two new feature flags for appeals FO - 'has-appeal-form-v2' and 's78-appeal-form-v2'.  The intention is for 'has-appeal-form-v2' to replace 'appeal-form-v2' (which will be deleted at a later date).
=> create has and s78 appeal form v2 feature flags

app/stacks/global/front-door/waf-policy.tf
Add exclusions to WAF policy for applicant.organisationName
https://pins-ds.atlassian.net/browse/APPLICS-35
=> feat(applications/bo): add exclusions for applicant.organisationName in back office only (APPLICS-35)

app/components/appeals-app-services/README.md, app/components/appeals-app-services/app-service.tf, app/components/appeals-app-services/locals.tf
https://pins-ds.atlassian.net/browse/A2-2010
Overrides TASK_SUBMIT_TO_HORIZON_TRIGGER_ACTIVE to always be false in the staging slot
This is so the cron job does not run twice and duplicate appeals
=> feat(appeals): ensure horizon trigger is false in staging slot

app/components/appeals-app-services/region.tf, app/components/applications-app-services/region.tf, app/components/back-office-app-services/region.tf, app/modules/front-door-premium/region.tf, app/modules/front-door/region.tf, app/stacks/global/back-office/region.tf, app/stacks/global/front-door-premium/main.tf, app/stacks/global/front-door/region.tf, app/stacks/uk-south/appeals-service/region.tf, app/stacks/uk-south/applications-service/region.tf, app/stacks/uk-south/back-office/region.tf, app/stacks/uk-south/common/region.tf, app/stacks/uk-west/appeals-service/region.tf, app/stacks/uk-west/applications-service/region.tf, app/stacks/uk-west/back-office/region.tf, app/stacks/uk-west/common/region.tf
replaces the multiple related dependabot PRs
=> chore(deps): bump claranet/regions/azurerm from 4.2.1 to 8.0.2

pipelines/infra-cd.yml, pipelines/infra-ci-plan.yml
Changes to support FD Classic migration, some stacks are only needed in prod now.
=> feat: ignore front-door and front-door-https stacks in non-prod environments
