app/stacks/appeals-service/network.tf
app/stacks/common/app-service.tf
pipelines/infra-cd.yml
pipelines/infra-ci.yml
pipelines/variables/dev.yml
pipelines/variables/production.yml
pipelines/variables/test.yml

- Uses wrapper template for CD pipeline
- Remove variable for service connection as AzureCLI task cannot take dynamic values (instead we construct the name via parameters in the template)
- Fix a few minor Terraform Plan glitches (i.e. stop it updating some resources every deployment)

Use template for CD pipeline

---

app/modules/app-service-backend/README.md
app/modules/app-service-frontend/README.md
app/stacks/appeals-service/README.md
app/stacks/appeals-service/cosmosdb.tf
app/stacks/common/README.md

- Add README files for each module with terraform-docs hooks
- Skip an issue reported by Checkov in CI pipeline - CKV_AZURE_140: only applicable to CosmosDB using the SQL API

Add tf-docs readme files

---

pipelines/infra-cd.yml
pipelines/infra-ci.yml
pipelines/variables/dev.yml
pipelines/variables/production.yml
pipelines/variables/test.yml

- Variables moved inside templates repo.
- Some small changes to parameters
- Production environment renamed to Prod

Update pipelines after template changes

---

app/modules/node-app-service/main.tf
app/stacks/appeals-service/README.md
app/stacks/appeals-service/subnet.tf
app/stacks/appeals-service/terragrunt.hcl
app/stacks/appeals-service/variables.tf
app/stacks/applications-service/README.md
app/stacks/applications-service/app-service.tf
app/stacks/applications-service/data.tf
app/stacks/applications-service/locals.tf
app/stacks/applications-service/subnet.tf
app/stacks/applications-service/terragrunt.hcl
app/stacks/applications-service/variables.tf
app/stacks/applications-service/variables/dev.hcl
app/stacks/applications-service/variables/prod.hcl
app/stacks/applications-service/variables/test.hcl
app/stacks/common/README.md
app/stacks/common/data.tf
app/stacks/common/key-vault.tf
app/stacks/common/locals.tf
app/stacks/common/outputs.tf
config/terragrunt.hcl
config/variables/prod.hcl
pipelines/infra-cd.yml

- Added a Key Vault to the common stack, and all the required secrets are also created in this stack with placeholder values.
- List of all Secret URIs are then output as a variable including the Microsoft reference string format so they can be consumed by other stacks
- Updated CD pipeline to deploy individual stacks
- Added App Settings for the Applications Service Backend web app

App settings applications service backend and Key Vault

---

app/modules/node-app-service/README.md
app/modules/node-app-service/main.tf
app/modules/node-app-service/variables.tf
app/stacks/appeals-service/README.md
app/stacks/appeals-service/app-service.tf
app/stacks/appeals-service/terragrunt.hcl
app/stacks/appeals-service/variables.tf
app/stacks/applications-service/README.md
app/stacks/applications-service/app-service.tf
app/stacks/applications-service/terragrunt.hcl
app/stacks/applications-service/variables.tf
app/stacks/applications-service/variables/dev.hcl
app/stacks/applications-service/variables/prod.hcl
app/stacks/applications-service/variables/test.hcl
app/stacks/common/README.md
app/stacks/common/additional-providers.tf
app/stacks/common/data.tf
app/stacks/common/locals.tf
app/stacks/common/network.tf
app/stacks/common/outputs.tf
app/stacks/common/resource-group.tf
app/stacks/common/variables.tf
config/variables/global.hcl

- Creates a peering resource with the tooling VNet

Add tooling env peering

---

pipelines/infra-cd.yml
pipelines/infra-ci.yml

- Pipeline now runs on a custom image and the agent pool for this is defined in the templates

Remove containers and MS hosted agent pools

---

app/modules/node-app-service/README.md
app/modules/node-app-service/main.tf
app/modules/node-app-service/outputs.tf
app/stacks/appeals-service/README.md
app/stacks/appeals-service/app-service.tf
app/stacks/appeals-service/azure-defender.tf
app/stacks/appeals-service/cosmosdb.tf
app/stacks/appeals-service/function-app.tf
app/stacks/appeals-service/locals.tf
app/stacks/appeals-service/service-bus.tf
app/stacks/appeals-service/storage-account.tf
app/stacks/appeals-service/storage-accounts.tf
app/stacks/appeals-service/terragrunt.hcl
app/stacks/appeals-service/variables.tf
app/stacks/applications-service/app-service.tf
app/stacks/applications-service/terragrunt.hcl
app/stacks/common/README.md
app/stacks/common/key-vault.tf
app/stacks/common/locals.tf

- Add Function Apps
- Add Service Bus
- Add some missing tags

Add required infrastructure for appeals service

---

app/stacks/appeals-service/README.md
app/stacks/appeals-service/app-service.tf
app/stacks/appeals-service/locals.tf
app/stacks/appeals-service/variables.tf
app/stacks/appeals-service/variables/dev.hcl
app/stacks/appeals-service/variables/prod.hcl
app/stacks/appeals-service/variables/test.hcl
app/stacks/applications-service/README.md
app/stacks/applications-service/app-service.tf
app/stacks/applications-service/locals.tf
app/stacks/applications-service/variables.tf
app/stacks/applications-service/variables/dev.hcl
app/stacks/applications-service/variables/prod.hcl
app/stacks/applications-service/variables/test.hcl
app/stacks/common/locals.tf
app/stacks/front-door/locals.tf
config/terragrunt.hcl
config/variables/dev.hcl
config/variables/prod.hcl
config/variables/test.hcl

- Add required app settings for the Appeals Service API

Add settings for Appeals Service API

---

app/components/appeals-app-services/app-service.tf
app/components/appeals-app-services/locals.tf
app/components/applications-app-services/app-service.tf
app/components/applications-app-services/locals.tf
app/components/networking/README.md
app/components/networking/outputs.tf
app/components/networking/variables.tf
app/components/networking/vpn-gateway.tf
app/modules/node-app-service/README.md
app/modules/node-app-service/main.tf
app/modules/node-app-service/variables.tf
app/stacks/uk-south/common/networking.tf
app/stacks/uk-west/appeals-service/terragrunt.hcl
app/stacks/uk-west/applications-service/terragrunt.hcl
app/stacks/uk-west/applications-service/vpn-gateway.tf
app/stacks/uk-west/common/networking.tf
pipelines/infra-cd.yml

- Fix terragrunt config for UK West stacks
- Fix App Service initialisation - Without the `linux_fx_version` key, the App service was coming out as a Windows image, so the deployment wasn't working. Have added this back.
- Some pipeline tweaks

Fix Terragrunt config for UK West and App Service initialisation

---

app/components/applications-app-services/locals.tf

Fixed applications-api settings for public URLs to include prefix of protocol and suffix of trailing slash

Fixed applications-api settings for public URLs

---

app/components/networking/README.md
app/components/networking/network.tf
app/components/networking/variables.tf
app/stacks/uk-south/common/README.md
app/stacks/uk-south/common/networking.tf
app/stacks/uk-south/common/variables.tf
app/stacks/uk-west/common/README.md
app/stacks/uk-west/common/networking.tf
app/stacks/uk-west/common/variables.tf
config/variables/global.hcl

- Add peering resource in other direction using the available provider for the Tooling subscription

Add peering in both directions in networking component

---

app/components/applications-app-services/locals.tf

Added protocol prefix and slash suffix to HOST_URL setting value of Applications Web App

Fix Applications Web App Setting for Host URL

---

app/components/appeals-app-services/README.md
app/components/appeals-app-services/function-app.tf
app/modules/node-app-service/monitoring.tf
app/modules/node-function-app/README.md
app/modules/node-function-app/monitoring.tf
app/modules/node-function-app/variables.tf

- Add basic metric and activity log alerts to the Node Function App module.
- Tune metric alert thresholds for App Service and Function Apps.

Basic monitoring for Function Apps

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/locals.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/README.md
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-south/back-office/variables.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/app-service.tf
app/stacks/uk-west/back-office/variables.tf

-  Add app settings for Back Office Web and API - basing these on the .env files in the back-office repo

Add app settings for Back Office apps

---

app/components/appeals-app-services/README.md
app/components/appeals-app-services/function-app.tf
app/components/appeals-app-services/service-bus.tf
app/components/appeals-app-services/variables.tf
app/modules/node-function-app/README.md
app/modules/node-function-app/locals.tf
app/modules/node-function-app/main.tf
app/modules/node-function-app/variables.tf
app/stacks/uk-south/appeals-service/README.md
app/stacks/uk-south/appeals-service/app-service.tf
app/stacks/uk-south/appeals-service/terragrunt.hcl
app/stacks/uk-south/appeals-service/variables.tf
app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/app-service.tf
app/stacks/uk-west/appeals-service/outputs.tf

- Fix storage access
- Fix name of queues
- Fix name of service connection
- Delete unnecessary queues and add missing queue

Fix appeals horizon functions

---

config/variables/stacks/common/dev.hcl
config/variables/stacks/common/prod.hcl
config/variables/stacks/common/test.hcl

- Remove Lester.March@kinandcarta.com from alert groups.

Update alert group membership

---

app/components/appeals-app-services/function-app.tf
app/modules/node-function-app/main.tf
app/modules/node-function-app/variables.tf

- Add vnet integration to the function app, so outbound traffic to resources in the network i.e. horizon can succeed

Add vnet integration for function app

---

app/components/back-office-app-services/locals.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-south/back-office/variables.tf
app/stacks/uk-west/back-office/app-service.tf
app/stacks/uk-west/back-office/variables.tf
config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/test.hcl

Updated the env variables across the different environments to include the three new AD group IDs and rename the three existing ones

Feature/boas 113 add group i IDs to the deployment containers

---

app/components/applications-app-services/locals.tf
app/components/applications-app-services/variables.tf
app/stacks/uk-south/applications-service/README.md
app/stacks/uk-south/applications-service/app-service.tf
app/stacks/uk-south/applications-service/variables.tf
app/stacks/uk-west/applications-service/README.md
app/stacks/uk-west/applications-service/app-service.tf
app/stacks/uk-west/applications-service/variables.tf
config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/prod.hcl
config/variables/stacks/applications-service/test.hcl

Add environment variable for feature toggle that shows/hides the 'Save & Exit' button on Applications registration journey

ASB-411: Environment variable to toggle save-and-exit button on applications

---

config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/test.hcl

Set document lib and representation flags to true in dev and test

feat(set flags to true): Set document lib and representation flags to true in dev and test

---

app/components/appeals-app-services/locals.tf
app/stacks/uk-south/appeals-service/README.md
app/stacks/uk-south/appeals-service/app-service-config.tf
app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/app-service-config.tf

- Add an App Configuration instance for managing feature flags for App Services.
- Add Key Vault secret for App Configuration connection string.
- Add environment variables to Appeals App Services with the connection string to App Configuration.

Appeals App Service Configuration and environment variables

---

app/stacks/uk-south/common/README.md
app/stacks/uk-south/common/app-service.tf
app/stacks/uk-south/common/variables.tf
app/stacks/uk-west/common/README.md
app/stacks/uk-west/common/app-service.tf
app/stacks/uk-west/common/variables.tf
config/variables/dev.hcl
config/variables/prod.hcl
config/variables/stacks/common/prod.hcl
config/variables/test.hcl

- Abstract the App Service Plan SKU value to the environment configuration files
- Increase the Pre-Production ASP SKU to "P2v2" (2CPU/7GB)
- Increase the Production ASP SKU to "P3v3" (8CPU/32GB)

App Service Plan SKU per-environment

---

app/components/applications-app-services/README.md
app/components/applications-app-services/locals.tf
app/components/applications-app-services/variables.tf
app/stacks/uk-south/applications-service/README.md
app/stacks/uk-south/applications-service/app-service.tf
app/stacks/uk-south/applications-service/redis-cache.tf
app/stacks/uk-south/applications-service/secrets.tf
app/stacks/uk-south/applications-service/variables.tf
app/stacks/uk-west/applications-service/README.md
app/stacks/uk-west/applications-service/app-service.tf
app/stacks/uk-west/applications-service/redis-cache.tf
app/stacks/uk-west/applications-service/secrets.tf
app/stacks/uk-west/applications-service/terragrunt.hcl
app/stacks/uk-west/applications-service/variables.tf
config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/prod.hcl
config/variables/stacks/applications-service/test.hcl

- redis cache instance for the applications service
- with private endpoint for connection to the applications-wfe App Service
- new secret in key vault to store the redis connection string

feature(applications-service): add redis cache for session storage

---

app/stacks/uk-south/applications-service/locals.tf
app/stacks/uk-south/applications-service/secrets.tf
app/stacks/uk-west/applications-service/locals.tf
app/stacks/uk-west/applications-service/secrets.tf

provide sql connection string in two formats. Prisma needs jbdc format, Function App needs ADO.NET format

fix(applications-service): sql connection string format

---

app/components/appeals-app-services/locals.tf
config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl

Turn off tag manager flag and use new GA4 code

task(appeals-service): update to GA4 code

---

app/components/back-office-app-services/locals.tf
app/modules/node-app-service/main.tf
app/stacks/global/front-door/front-door.tf
app/stacks/global/front-door/locals.tf

Remove loops from backend and routing rules

Remove custom hostname creation for back-office appeals.

---

app/components/applications-app-services/README.md
app/components/applications-app-services/locals.tf
app/components/applications-app-services/variables.tf
app/stacks/uk-south/applications-service/README.md
app/stacks/uk-south/applications-service/app-service.tf
app/stacks/uk-south/applications-service/variables.tf
app/stacks/uk-west/applications-service/README.md
app/stacks/uk-west/applications-service/app-service.tf
app/stacks/uk-west/applications-service/variables.tf
config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/prod.hcl
config/variables/stacks/applications-service/test.hcl

- adds notify id for the new 'subscription create' (get updates) email
- tidy up some very similar env vars and combine into one

feat(applications-service): add subscription create email notify id and tidy up env vars

---

app/components/back-office-app-services/iam.tf

Set the permissions to write to service bus to the back_office_appeals_api principal

fix(appeals): permissions for service bus

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl

Add new feature flag for HAS questionnaire.
Includes a linting fix

feat(appeals-service):add has questionnaire feature flag

---

app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/outputs.tf
app/stacks/uk-west/back-office/service-bus.tf

add `nsip-representation` topic to the back office service bus

feat(back-office): add nsip-representation topic

---

.gitignore
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/outputs.tf
app/stacks/uk-west/back-office/storage-account.tf

Create a blob storage resource for temporarily holding timetable submission files before they're 'submitted'.

Submissions storage

---

app/stacks/uk-south/appeals-service/terragrunt.hcl
app/stacks/uk-south/back-office/README.md
app/stacks/uk-south/back-office/outputs.tf

clam av does not exist in uk south for back office

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/deadline-submissions-function/function-app.tf
app/components/back-office-app-services/deadline-submissions-function/iam.tf
app/components/back-office-app-services/deadline-submissions-function/provider.tf
app/components/back-office-app-services/deadline-submissions-function/variables.tf
app/components/back-office-app-services/func-deadline-submissions.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-west/applications-service/terragrunt.hcl
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/app-service.tf
app/stacks/uk-west/back-office/outputs.tf
app/stacks/uk-west/back-office/service-bus.tf

Create infra for the new deadline submissions function:
- Function
- Function storage
- Service bus topic & subscription
- IAM roles

Deadline Submissions Function

---

app/stacks/global/front-door/.terraform.lock.hcl
app/stacks/global/front-door/waf-policy.tf

Specific WAF rule exception for [ASB-1692](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-1692).

fix(waf): exception to allow back office project update content

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/deadline-submissions-function/function-app.tf
app/components/back-office-app-services/deadline-submissions-function/variables.tf
app/components/back-office-app-services/doc-scanning.tf
app/components/back-office-app-services/document-check-function/function-app.tf
app/components/back-office-app-services/document-check-function/variables.tf
app/components/back-office-app-services/func-deadline-submissions.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-south/back-office/terragrunt.hcl
app/stacks/uk-south/back-office/variables.tf
app/stacks/uk-west/back-office/app-service.tf

I've set up publishing events from the deadline-submissions function and document-check function in the back-office repo. This PR gives the two functions the environment variables they need to connect to Service Bus.

Deadline submissions variables

---

app/components/back-office-app-services/locals.tf

Add env vars for BO Appeals Gov Notify integration

feat(bo/appeals): env vars for gov notify

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/bo-appeals-casedata-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-casedata-import-function/iam.tf
app/components/back-office-app-services/bo-appeals-casedata-import-function/provider.tf
app/components/back-office-app-services/bo-appeals-casedata-import-function/variables.tf
app/components/back-office-app-services/bo-appeals-hrdata-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-hrdata-import-function/iam.tf
app/components/back-office-app-services/bo-appeals-hrdata-import-function/provider.tf
app/components/back-office-app-services/bo-appeals-hrdata-import-function/variables.tf
app/components/back-office-app-services/bo-appeals-lpaq-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-lpaq-import-function/iam.tf
app/components/back-office-app-services/bo-appeals-lpaq-import-function/provider.tf
app/components/back-office-app-services/bo-appeals-lpaq-import-function/variables.tf
app/components/back-office-app-services/func-bo-appeals-casedata-import.tf
app/components/back-office-app-services/func-bo-appeals-hrdata-import.tf
app/components/back-office-app-services/func-bo-appeals-lpaq-import.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/app-service.tf
app/stacks/uk-west/back-office/outputs.tf
app/stacks/uk-west/back-office/service-bus.tf

Added consumer functions for:
- Pulling appellant case data
- Pulling LPA questionnaire data
Registered topics for the above commands (FO).

feat(appeals): back-office consumer functions

---

app/components/back-office-app-services/bo-appeals-casedata-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-hrdata-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-lpaq-import-function/function-app.tf

Adjust the source of newly created backoffice appeals functions.

chore(appeals): back-office consumer functions source

---

app/components/back-office-app-services/deadline-submissions-function/iam.tf

The existing 'owner' role should be enough, but for some reason I'm still seeing auth errors.

Add sender permission to deadline-submissions-function

---

config/variables/stacks/back-office/prod.hcl

update email template ID for back office prod

chore(back-office): update prod email template for project updates

---

app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/storage-account.tf

Couldn't find an equivalent in uks

feat(appeals-fo): add listed buildings container

---

app/modules/node-app-service/README.md
app/modules/node-app-service/locals.tf
app/modules/node-app-service/outputs.tf

Reverts Planning-Inspectorate/infrastructure-environments#419

Revert "adding key vault secrets for docker registry credentials"

---

app/stacks/uk-south/back-office/redis-cache.tf
app/stacks/uk-west/back-office/.terraform.lock.hcl
app/stacks/uk-west/back-office/redis-cache.tf

Had used the same name for two resources.
N/A

fix(back-office): use unique names for virtual network links

---

app/components/applications-app-services/function-app.tf

ASB-1796
Update Function App to Node 18

chore(applications-service): update applications function app to node 18

---

app/stacks/uk-south/back-office/redis-cache.tf
app/stacks/uk-west/back-office/redis-cache.tf

Use unique names to avoid private link conflicts on the common virtual network.
[BOAS-1034](https://pins-ds.atlassian.net/browse/BOAS-1034)
N/A

fix(back-office): use unique names for dns zones

---

app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/outputs.tf
app/stacks/uk-west/back-office/service-bus.tf

New service bus topic for BO appeals service users.

feature(appeals): service bus topic for service users

---

app/components/back-office-app-services/publish-document-function/function-app.tf
app/components/back-office-app-services/publish-document-function/iam.tf

Create a subscription for a new document unpublish function, triggered by a document Update event with an `{ unpublished: true }` flag

Create a subscription for a new document unpublish function

---

app/stacks/uk-south/appeals-service/README.md
app/stacks/uk-south/appeals-service/secrets.tf
app/stacks/uk-west/appeals-service/secrets.tf

Remove secret definition in UK south and use direct lookup for the module in uk west

fix(appeals-fo): fix module lookup for key vault secret

---

app/components/back-office-app-services/app-service.tf

Update infra module tag for back office app services

update module tag for back office

---

app/components/applications-app-services/README.md
app/components/applications-app-services/locals.tf
app/components/applications-app-services/variables.tf
app/stacks/uk-south/applications-service/README.md
app/stacks/uk-south/applications-service/app-service.tf
app/stacks/uk-south/applications-service/variables.tf
app/stacks/uk-west/applications-service/README.md
app/stacks/uk-west/applications-service/app-service.tf
app/stacks/uk-west/applications-service/variables.tf
config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/prod.hcl
config/variables/stacks/applications-service/test.hcl

feat(applications-service): add planned outage flag

---

app/modules/node-function-app/monitoring.tf
app/stacks/global/front-door/monitoring.tf
app/stacks/uk-west/back-office/monitoring.tf
app/stacks/uk-west/back-office/secrets.tf

remove version from ignore_changes on bo kv resource to remove redundant warning

remove version from ignore_changes on bo kv resource to remove redundant warning

---

app/modules/node-app-service/monitoring.tf
app/stacks/uk-west/appeals-service/secrets.tf
app/stacks/uk-west/applications-service/README.md
app/stacks/uk-west/applications-service/secrets.tf
app/stacks/uk-west/common/key-vault.tf

Updated ignore_changes attributes on the rest of the stacks to resolve pipeline warnings after conducting a test on the last pull request

Updated ignore_changes attributes to resolve pipeline warnings

---

config/variables/stacks/applications-service/prod.hcl

fix: add pliot case to applications migration list

---

app/components/back-office-app-services/publish-document-function/function-app.tf

Resolve duplicate names of subscription rules in publish/unpublish

---

app/components/back-office-app-services/malware-scanning.tf

There's an error during deployment because I've passed the values for the ARM template parameters incorrectly. Annoyingly this doesn't get flagged up during build, only during deployment.

Use correct syntax for passing parameters to ARM template

---

app/components/appeals-app-services/locals.tf

add newly required environment variables to appeals_service_api

---

app/components/back-office-app-services/malware-scanning.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-west/back-office/app-service.tf

Pass storage account name instead of ID to malware scanning template

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/malware-detected-function/event-grid.tf
app/components/back-office-app-services/malware-detected-function/function-app.tf
app/components/back-office-app-services/malware-detected-function/iam.tf
app/components/back-office-app-services/malware-detected-function/provider.tf
app/components/back-office-app-services/malware-detected-function/variables.tf
app/components/back-office-app-services/malware-detected.tf

Create Event Grid subscription and Azure Function resources for responding when a malicious file is detected.

Create resources for malware detected Azure function

---

app/stacks/uk-west/back-office/event-grid.tf

Give the `malware-scanning-topic` Event Grid topic a unique name per environment

fix: event grid topic name unique per env

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/iam.tf

Add a role to allow the back office stack to publish events to the malware scanning Event Grid topic.

Add 'EventGrid Data Sender' role for publishing events to malware topic

---

app/components/back-office-app-services/malware-detected-function/iam.tf
app/stacks/uk-west/back-office/event-grid.tf

Enable local authentication on malware event grid topic.

Enable local authentication on malware event grid topic

---

app/stacks/uk-west/back-office/event-grid.tf

Removing this line to see if it's the culprit for a 403 being thrown when Microsoft Defender tries to publish events.
It might be a security risk to leave it like this, if removing this line works we should figure out how to allow only the traffic we want.

Enable public network access on Event Grid topic for malware scanning

---

app/components/back-office-app-services/malware-detected-function/function-app.tf

Use Node version 18 for malware detected function. Version 14 was copied from the document check function, but that was just needed for ClamAV.

Use Node version 18 for malware detected function

---

app/stacks/uk-south/appeals-service/terragrunt.hcl

fix(appeals-fo): add mocks for sql outputs in uks

---

app/stacks/uk-south/appeals-service/database.tf
app/stacks/uk-west/appeals-service/database.tf
config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl

fix(appeals-fo): add sql backup week of year

---

app/components/appeals-app-services/README.md
app/components/appeals-app-services/function-app.tf
app/components/applications-app-services/README.md
app/components/applications-app-services/function-app.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf
app/components/back-office-app-services/bo-appeals-casedata-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-hrdata-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-lpaq-import-function/function-app.tf
app/components/back-office-app-services/deadline-submissions-function/function-app.tf
app/components/back-office-app-services/document-check-function/function-app.tf
app/components/back-office-app-services/handle-subscriptions-function/function-app.tf
app/components/back-office-app-services/malware-detected-function/function-app.tf
app/components/back-office-app-services/odw-subscriber-function/function-app.tf
app/components/back-office-app-services/publish-document-function/function-app.tf

updated function apps to call the latest module changes

updated function apps to call the latest module changes

---

app/components/back-office-app-services/notify-subscribers-function/function-app.tf

Updated the notify-function-source to point to the infrastructure-modules repository

Updated the notify-function-source to point to the infrastructure-modules repository

---

app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/service-bus.tf

Temporarily allow consumption for ODW

---

app/components/appeals-app-services/locals.tf

feat(appeals-fo): temp - revert session

---

app/components/appeals-app-services/locals.tf

This reverts commit a6784e0549e5d56c0e120ca33144417e71cdac97.

Revert "feat(appeals-fo): temp - revert session"

---

app/components/appeals-app-services/README.md
app/components/appeals-app-services/function-app.tf
app/components/applications-app-services/README.md
app/components/applications-app-services/function-app.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf
app/components/back-office-app-services/bo-appeals-casedata-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-hrdata-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-lpaq-import-function/function-app.tf
app/components/back-office-app-services/deadline-submissions-function/function-app.tf
app/components/back-office-app-services/document-check-function/function-app.tf
app/components/back-office-app-services/handle-subscriptions-function/function-app.tf
app/components/back-office-app-services/malware-detected-function/function-app.tf
app/components/back-office-app-services/notify-subscribers-function/function-app.tf
app/components/back-office-app-services/odw-subscriber-function/function-app.tf
app/components/back-office-app-services/publish-document-function/function-app.tf

Update node function app source to 1.7

Update node function app source to 1.7

---

config/variables/stacks/applications-service/prod.hcl

fix: add migrated cases to applications FO

---

app/components/back-office-app-services/applications-migration-function/iam.tf

Test increasing permission to owner

---

app/stacks/uk-south/appeals-service/.terraform.lock.hcl
app/stacks/uk-south/appeals-service/app-service.tf
app/stacks/uk-west/appeals-service/.terraform.lock.hcl
app/stacks/uk-west/appeals-service/app-service.tf
config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl

- Added enrol users
- Sorted vars alphabetically for easier reading
- Performed a terraform init in the appeals stacks leading to a lock file change, presume this is ok

feat(appeals-fo): add enrol-users feature flag, organise some vars alphabetically

---

app/components/back-office-app-services/locals.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/monitoring.tf
app/stacks/uk-west/back-office/secrets.tf

* feat(api/applications): set up Application Insights for Back Office
* Add a daily data cap of 10GB to App Insights

Set up Application Insights for Back Office

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/bo-appeals-doc-processing-function/function-app.tf
app/components/back-office-app-services/bo-appeals-doc-processing-function/iam.tf
app/components/back-office-app-services/bo-appeals-doc-processing-function/variables.tf
app/components/back-office-app-services/func-bo-appeals-document-processing.tf
app/components/back-office-app-services/locals.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-west/back-office/app-service.tf

Fixes for https://dev.azure.com/planninginspectorate/infrastructure/_build/results?buildId=69466&view=results

fix(appeals): adding ID and names of resources

---

app/components/back-office-app-services/bo-appeals-doc-processing-function/iam.tf
app/stacks/uk-west/back-office/app-service.tf

Set permissions on resource manager ID rather than resource ID

fix(appeals): setting permissions on resmgr_id

---

app/stacks/uk-west/back-office/app-service.tf

Provide the ARM ID of the container

---

app/components/back-office-app-services/iam.tf

Adds contributor permissions to a new blob container for appeal user groups

fix(appeals): sets permissions on new storage container

---

app/stacks/uk-south/applications-service/redis-cache.tf

fix: ensure redis dns zone is always created in uk-south

---

app/stacks/uk-south/back-office/data.tf
app/stacks/uk-west/back-office/data.tf

Try adding resource group to find dns zone.

fix: don't look for redis dns zone in tooling sub

---

app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/outputs.tf

Adds output for new appeals document container

fix(appeals): adds output for appeals docs resource manager id

---

app/stacks/uk-south/back-office/data.tf
app/stacks/uk-west/back-office/data.tf

fix(back-office): specify resource group for private dns zone

---

config/variables/stacks/applications-service/prod.hcl

- [] Bug fix (non-breaking change which fixes an issue)

fix(applications): Add activated caseReferences to migrated variable

---

app/stacks/global/front-door/locals.tf

Update locals file to match frontend output of terragrunt.hcl

Update locals file to match frontend output of terragrunt.hcl

---

app/stacks/global/front-door-https/terragrunt.hcl
app/stacks/global/front-door/front-door.tf
app/stacks/global/front-door/outputs.tf

temporarily hashed out frontend_endpoints for CommentPlanningAppeal

hashed out frontend_endpoints for CommentPlanningAppeal

---

app/stacks/global/front-door/front-door.tf

Point the health check to the /health endpoint instead of API root
Relies on the endpoint introduced here https://github.com/Planning-Inspectorate/back-office/pull/1810

Point the health check to the /health endpoint instead of API root

---

config/variables/dev.hcl
config/variables/test.hcl

removed comment_planning_appeal_public_url from locals in config

removed comment_planning_appeal_public_url from locals in config

---

app/components/back-office-app-services/func-bo-appeals-document-processing.tf

Fixing correct endpoint for appeals api

fix(appeals): correct api host

---

app/components/back-office-app-services/locals.tf

Enable App Insights and health checks for the back office web service.
Just duplicating the changes I already did for the API.

Enable App Insights and health checks for the back office web service

---

app/components/applications-app-services/function-app.tf

Ticket: https://pins-ds.atlassian.net/browse/ASB-2011
Quick update to https://github.com/Planning-Inspectorate/infrastructure-environments/pull/551 - updates sqlFilters for `applications-nsip-service-user-subscription-rule` to combine `Represented` and `Representative` to `RepresentationContact`.

feat: update service user sqlFilter

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/bo-appeals-doc-processing-function/variables.tf
app/components/back-office-app-services/bo-appeals-scheduler-function/function-app.tf
app/components/back-office-app-services/bo-appeals-scheduler-function/iam.tf
app/components/back-office-app-services/bo-appeals-scheduler-function/provider.tf
app/components/back-office-app-services/bo-appeals-scheduler-function/variables.tf
app/components/back-office-app-services/func-bo-appeals-scheduler.tf

A new AZ function to allow deployment of timer triggers...

feature(appeals/bo): function for scheduled jobs

---

app/components/appeals-app-services/app-service.tf
app/components/appeals-app-services/function-app.tf
app/components/applications-app-services/app-service.tf
app/components/applications-app-services/function-app.tf
app/components/back-office-app-services/app-service.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf
app/components/back-office-app-services/bo-appeals-casedata-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-doc-processing-function/function-app.tf
app/components/back-office-app-services/bo-appeals-scheduler-function/function-app.tf
app/components/back-office-app-services/bo-appeals-userdata-import-function/function-app.tf
app/components/back-office-app-services/deadline-submissions-function/function-app.tf
app/components/back-office-app-services/document-check-function/function-app.tf
app/components/back-office-app-services/handle-subscriptions-function/function-app.tf
app/components/back-office-app-services/malware-detected-function/function-app.tf
app/components/back-office-app-services/notify-subscribers-function/function-app.tf
app/components/back-office-app-services/odw-subscriber-function/function-app.tf
app/components/back-office-app-services/publish-document-function/function-app.tf

updated module sources for app service and function app to 1.9
The update to the module consist of each module having their test folder within the specific module

updated module sources for app service and function app to 1.9

---

config/variables/stacks/applications-service/prod.hcl

(chore): activate app insights for applications

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/bo-appeals-doc-processing-function/function-app.tf
app/components/back-office-app-services/bo-appeals-doc-processing-function/variables.tf
app/components/back-office-app-services/bo-appeals-scheduler-function/function-app.tf
app/components/back-office-app-services/bo-appeals-scheduler-function/variables.tf
app/components/back-office-app-services/func-bo-appeals-document-processing.tf
app/components/back-office-app-services/func-bo-appeals-scheduler.tf
app/components/back-office-app-services/locals.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-west/back-office/app-service.tf

- Adds backoffice api config to access blob storage
- Renames some of the backoffice appeals variables

feat(bo-appeals): adding blob connection to api, renaming vars

---

app/components/back-office-app-services/bo-appeals-doc-processing-function/iam.tf

New function to copy docs is triggered by SB topic... Missed permissions for IAM.

fix(backoffice/appeals): missing IAM perms for service bus topic

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/func-register-representation.tf
app/components/back-office-app-services/register-representation-function/function-app.tf
app/components/back-office-app-services/register-representation-function/iam.tf
app/components/back-office-app-services/register-representation-function/provider.tf
app/components/back-office-app-services/register-representation-function/variables.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-west/back-office/app-service.tf

ASB-2069
infra for new function to consume events on the `register-representation` topic
Terraform plan: https://dev.azure.com/planninginspectorate/infrastructure/_build/results?buildId=70882&view=logs&j=d8c8df2e-1b9e-55db-c620-fddadb65a07b&t=4249e1c0-7c45-519a-22b6-aa3426e7584b

feat: register-representation subscriber function

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/iam.tf

Grant the Inspector user write access to blob storage

Grant the Inspector user write access to blob storage

---

app/components/appeals-app-services/README.md
app/components/applications-app-services/README.md
app/components/applications-app-services/function-app.tf

Ticket: https://pins-ds.atlassian.net/browse/ASB-2089
Adds advice unpublish subscription to app service BO consumer functions.

feat: advice unpublish subscription

---

config/variables/stacks/back-office/test.hcl

Set odw_synapse_integration_enabled true in test.

feat(bo): enable odw integration in test

---

app/components/back-office-app-services/applications-migration-function/iam.tf

docs: comment about odw permissions

---

config/variables/prod.hcl

fix: comment_planning_appeal_public_url empty for prod

---

config/variables/stacks/applications-service/prod.hcl

Add Migrated project Ids to migration list.
So that activated projects are not overwritten by a release.

fix: Add migrated projects Id to migration list

---

config/variables/prod.hcl

Temporary comment-planning-appeal prod url so that front-door can be deployed.

chore(appeals): add temporary comment-planning-appeal prod url

---

app/components/networking/README.md
app/components/networking/network.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/synapse-private-link.tf

Typo in synapse (only for terraform names)

fix: synapse typo

---

config/variables/stacks/applications-service/prod.hcl

Add migrated Applications projects to infrastructure

fix: Add migrated cases to applications

---

config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl

feat(appeals): deploy web-comment to all environments

---

config/variables/stacks/appeals-service/prod.hcl

feat(appeals-fo): set prod registration notify id

---

app/components/applications-app-services/README.md
app/components/applications-app-services/function-app.tf

Ticket: https://pins-ds.atlassian.net/browse/ASB-2173
PR updates existing representation subscription to filter only "Publish" type messages, and a new subscription is created for "Update" type messages.

feat: representation update subscription

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/locals.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/README.md
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-south/back-office/secrets.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/app-service.tf
app/stacks/uk-west/back-office/outputs.tf
app/stacks/uk-west/back-office/secrets.tf

Moving the DB connection string to be referenced via a Key Vault secret URI.

move db connection string to a key-vault secret

---

app/components/appeals-app-services/function-app.tf

feat(appeals): add api hostname for integration functions

---

app/components/appeals-app-services/function-app.tf
app/components/applications-app-services/function-app.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf
app/components/back-office-app-services/bo-appeals-casedata-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-doc-processing-function/function-app.tf
app/components/back-office-app-services/bo-appeals-scheduler-function/function-app.tf
app/components/back-office-app-services/bo-appeals-userdata-import-function/function-app.tf
app/components/back-office-app-services/deadline-submissions-function/function-app.tf
app/components/back-office-app-services/document-check-function/function-app.tf
app/components/back-office-app-services/handle-subscriptions-function/function-app.tf
app/components/back-office-app-services/malware-detected-function/function-app.tf
app/components/back-office-app-services/notify-subscribers-function/function-app.tf
app/components/back-office-app-services/odw-subscriber-function/function-app.tf
app/components/back-office-app-services/publish-document-function/function-app.tf
app/components/back-office-app-services/register-representation-function/function-app.tf

Run Function Apps from package by default - to speed up deployments.
https://learn.microsoft.com/en-gb/azure/azure-functions/run-functions-from-deployment-package

chore: update functions module to 1.11, run from package

---

pipelines/infra-ci.yml

Each PR branch would have two CI runs, this sorts that.

ci: only trigger ci on pr or main

---

app/components/appeals-app-services/README.md
app/components/appeals-app-services/locals.tf
app/components/appeals-app-services/variables.tf

feat(appeals-fo): increase max file size

---

app/components/back-office-app-services/applications-command-handler-functions/function-app.tf

Upgrade command handler function app version

---

app/stacks/global/front-door-https/front-door-https.tf
app/stacks/global/front-door-https/variables.tf
config/variables/stacks/front-door-https/dev.hcl
config/variables/stacks/front-door-https/prod.hcl
config/variables/stacks/front-door-https/test.hcl

https://pins-ds.atlassian.net/browse/DEV-92
Add config flags for using Azure managed SSL certs.

feat(front-door-https): add switch for azure managed certs

---

app/components/applications-app-services/README.md
app/components/applications-app-services/function-app.tf

Ticket: https://pins-ds.atlassian.net/browse/ASB-2172
PR adds subscription for unpublishing service users.

feat: service user unpublish sub added

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/applications-background-job-functions/function-app.tf
app/components/back-office-app-services/applications-background-job-functions/variables.tf
app/components/back-office-app-services/applications-command-handler-functions/function-app.tf
app/components/back-office-app-services/applications-command-handler-functions/variables.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf
app/components/back-office-app-services/func-applications-background-jobs.tf
app/components/back-office-app-services/func-applications-command-handlers.tf
app/components/back-office-app-services/locals.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/README.md
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-south/back-office/variables.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/app-service.tf
app/stacks/uk-west/back-office/secrets.tf
app/stacks/uk-west/back-office/variables.tf
config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/test.hcl

add key vault secret and variable to api and web apps

---

config/variables/stacks/front-door-https/test.hcl

https://pins-ds.atlassian.net/browse/DEV-92
Enable managed certs on test

feat(front-door-https): use managed certs on test

---

app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/secrets.tf

add secret for swagger api key

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl

feat(appeals-fo): add serve-back-office-documents feature flag

---

app/components/appeals-app-services/locals.tf

Temporarily bring back clamav rest server until code deployed to avoid any downtime on release

fix(appeals-fo): aapd-1237 bring back clamav rest until code released

---

app/stacks/uk-west/back-office/secrets.tf

ensure api key is not reset on deployment due to drift

---

app/components/back-office-app-services/applications-background-job-functions/iam.tf
app/components/back-office-app-services/applications-background-job-functions/variables.tf
app/components/back-office-app-services/applications-command-handler-functions/iam.tf
app/components/back-office-app-services/applications-command-handler-functions/variables.tf
app/components/back-office-app-services/func-applications-background-jobs.tf
app/components/back-office-app-services/func-applications-command-handlers.tf

add iam kv perms to azure functions calling be

---

app/stacks/uk-west/back-office/database.tf

Add a SystemAssigned identity to the back office SQL server
This should fix the broken pipeline.

Add a SystemAssigned identity to the back office SQL server

---

app/components/back-office-app-services/locals.tf
app/components/back-office-app-services/variables.tf
app/stacks/uk-south/back-office/app-service.tf
app/stacks/uk-south/back-office/variables.tf
app/stacks/uk-west/back-office/app-service.tf
app/stacks/uk-west/back-office/variables.tf
config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/test.hcl

add horizon url to back-office infra

---

app/components/back-office-app-services/README.md
app/components/back-office-app-services/applications-background-job-functions/function-app.tf
app/components/back-office-app-services/applications-background-job-functions/iam.tf
app/components/back-office-app-services/applications-background-job-functions/variables.tf
app/components/back-office-app-services/applications-command-handler-functions/function-app.tf
app/components/back-office-app-services/applications-command-handler-functions/iam.tf
app/components/back-office-app-services/applications-command-handler-functions/variables.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf
app/components/back-office-app-services/applications-migration-function/iam.tf
app/components/back-office-app-services/applications-migration-function/variables.tf
app/components/back-office-app-services/func-applications-background-jobs.tf
app/components/back-office-app-services/func-applications-command-handlers.tf
app/components/back-office-app-services/func-applications-migration.tf

fix functions to use imported read_secrets policy

---

app/components/appeals-app-services/locals.tf
app/components/applications-app-services/locals.tf

feat: add retry max_attempts and retry_status_cods

---

app/stacks/uk-south/back-office/README.md
app/stacks/uk-south/back-office/database.tf
app/stacks/uk-south/back-office/monitoring.tf
app/stacks/uk-south/back-office/terragrunt.hcl
app/stacks/uk-south/back-office/variables.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/database.tf
app/stacks/uk-west/back-office/monitoring.tf
app/stacks/uk-west/back-office/terragrunt.hcl
app/stacks/uk-west/back-office/variables.tf
config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/test.hcl

This reverts commit ec60ccbf54f2eb7ee240c55481c55fb19b59803a.
Replicate SQL monitoring changes in uk-south
These changes were previously approved but were reverted to allow the identity block to deploy.

Unrevert "Replicate SQL monitoring changes in uk-south"

---

app/stacks/uk-south/back-office/README.md
app/stacks/uk-south/back-office/database.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/database.tf

Rename SQL storage accounts in BO to avoid conflicts with appeals
Deployment to dev is failing because the current name for the storage account already exists.

Rename SQL storage accounts in BO to avoid conflicts with appeals

---

app/stacks/global/front-door/front-door.tf

FD deploy failing because of a bad rules name - not sure why it's an issue now.

fix(front-door): rules_engine doesn't like spaces in names

---

app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/outputs.tf
app/stacks/uk-west/back-office/service-bus.tf

- Added entries in Readme for new folder topic
- Added output "servicebus_topic_folders_id"
- Added resource "azurerm_servicebus_topic" "folders"
https://pins-ds.atlassian.net/browse/BOAS-1521
Using back-office applications, make sure the create, update and delete folder events are sent correctly

feat(applications/bo): add azure topic folder (BOAS-1521)

---

app/stacks/global/front-door/front-door.tf

re-enable the appeals WAF policy

feat(front-door): use appeals waf policy for appeals frontend

---

app/components/back-office-app-services/locals.tf

Add new secret names to existing_secret_names dictionary
This was missed in the previous PR and the error didn't surface until deployment.

Add new secret names to existing_secret_names dictionary

---

app/components/applications-app-services/locals.tf
app/components/back-office-app-services/README.md
app/components/back-office-app-services/locals.tf
app/stacks/uk-west/applications-service/README.md
app/stacks/uk-west/applications-service/database.tf
app/stacks/uk-west/applications-service/locals.tf
app/stacks/uk-west/applications-service/secrets.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/app-service.tf
app/stacks/uk-west/back-office/database.tf
app/stacks/uk-west/back-office/locals.tf
app/stacks/uk-west/back-office/outputs.tf
app/stacks/uk-west/back-office/secrets.tf

Revert recent SQL admin login changes. Would have replaced the SQL db.

Revert SQL Admin Changes

---

app/components/appeals-app-services/README.md
app/components/appeals-app-services/app-service.tf
app/components/appeals-app-services/function-app.tf
app/components/applications-app-services/README.md
app/components/applications-app-services/app-service.tf
app/components/applications-app-services/function-app.tf
app/components/back-office-app-services/README.md
app/components/back-office-app-services/app-service.tf
app/components/back-office-app-services/applications-background-job-functions/function-app.tf
app/components/back-office-app-services/applications-command-handler-functions/function-app.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf
app/components/back-office-app-services/bo-appeals-casedata-import-function/function-app.tf
app/components/back-office-app-services/bo-appeals-doc-processing-function/function-app.tf
app/components/back-office-app-services/bo-appeals-scheduler-function/function-app.tf
app/components/back-office-app-services/bo-appeals-userdata-import-function/function-app.tf
app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/database.tf
app/stacks/uk-west/appeals-service/monitoring.tf
app/stacks/uk-west/appeals-service/terragrunt.hcl
app/stacks/uk-west/appeals-service/variables.tf
app/stacks/uk-west/applications-service/README.md
app/stacks/uk-west/applications-service/database.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/monitoring.tf
app/stacks/uk-west/back-office/terragrunt.hcl
app/stacks/uk-west/back-office/variables.tf

- [fix: align severity level and recipient of SQL alerts](https://github.com/Planning-Inspectorate/infrastructure-environments/commit/55e86b190f8a49e587d8c9aaf23daacb3e0b0127)
- [fix: align severity level and recipient of horizon submission alerts](https://github.com/Planning-Inspectorate/infrastructure-environments/commit/b6642b555e0a89829a89867c9abf333b3d67ed55)
- [feat: add appeals back office SQL alerts](https://github.com/Planning-Inspectorate/infrastructure-environments/commit/b17df1c971cbb128c92a7ef4b43d5ec8e1982ca0)
- [feat: add applications front office SQL alerts](https://github.com/Planning-Inspectorate/infrastructure-environments/commit/dded63b98a367ea97abb16999af2d9a903fffa18)
- [chore: update apps and functions to 1.16, with alert …

Azure Alerts

---

config/variables/dev.hcl
config/variables/stacks/front-door-https/dev.hcl
config/variables/stacks/front-door-https/prod.hcl
config/variables/stacks/front-door-https/test.hcl
config/variables/test.hcl

Dev alert groups are empty, but we want to know the alerts do work and show up in portal.
Test alerts are useful as issues on test affect QA and the team.

chore: enable alerts in dev and test

---

app/stacks/uk-south/appeals-service/terragrunt.hcl
app/stacks/uk-south/applications-service/terragrunt.hcl
app/stacks/uk-south/back-office/terragrunt.hcl
app/stacks/uk-west/appeals-service/terragrunt.hcl
app/stacks/uk-west/applications-service/terragrunt.hcl
app/stacks/uk-west/common/README.md
app/stacks/uk-west/common/action-group.tf
app/stacks/uk-west/common/outputs.tf

chore: remove 'low' action group, now unused

---

pipelines/infra-cd.yml
pipelines/infra-ci.yml

https://pins-ds.atlassian.net/browse/DEV-136
Separate secrets libraries per environment for Infrastructure

chore: separate variable groups per environment and pipeline

---

app/stacks/uk-west/common/README.md
app/stacks/uk-west/common/key-vault.tf

fix(common): don't manage service principle access policy

---

config/variables/stacks/front-door-https/prod.hcl

use managed certs for appeals and applications front office in prod

feat(front-door-https): use managed certs for appeals and applications front office prod

---

app/stacks/uk-west/back-office/terragrunt.hcl
app/stacks/uk-west/common/locals.tf

feat(common): add action groups for data service

---

app/stacks/uk-west/back-office/locals.tf

Max five action groups per alert.
> Status=400 Code="BadRequest" Message="Only 5 action groups are allowed.

fix: max five action groups per alert

---

app/stacks/global/front-door/README.md
app/stacks/global/front-door/monitoring.tf
app/stacks/global/front-door/variables.tf

Automated alert for appeals WAF blocks

feat(appeals-fo): add azure alert for WAF blocks

---

pipelines/infra-ci-plan.yml

build: new pipeline for PR dev plan

---

config/variables/dev.hcl
config/variables/prod.hcl
config/variables/test.hcl

Appeals: Correct firewall error url

---

app/components/back-office-app-services/applications-migration-function/function-app.tf
config/variables/stacks/back-office/prod.hcl

chore(back-office): enable ODW integration in prod

---

app/stacks/global/front-door/outputs.tf

Accidental changes to dev/test

fix(front-door): don't change outputs unless new URL exists

---

app/components/appeals-app-services/locals.tf
app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/secrets.tf

https://pins-ds.atlassian.net/browse/AAPD-1195
- Adds a new backend app service for appeals - auth server
- Uses generated client id + secrets

feat(appeals-fo): add auth server

---

app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/service-bus.tf

chore(back-office): remove temporary RBAC assignments

---

app/stacks/global/front-door/waf-policy.tf

add waf exclusion for rule 942440 checking cookie

---

app/modules/front-door/front-door.tf
app/modules/front-door/variable.tf
app/stacks/global/back-office/published-documents-fd.tf

added domain

---

app/modules/front-door/front-door.tf
app/modules/front-door/variable.tf
app/stacks/global/back-office/published-documents-fd.tf
app/stacks/global/back-office/variables.tf

added blob storage endpoint for host_name of front door origin

---

app/modules/front-door/front-door.tf

added custom domain association

---

app/modules/front-door/front-door.tf

add custom domain argument to front door route block

---

app/modules/front-door/front-door.tf

added dns zone

---

app/modules/front-door/dns.tf

add dns cname record

---

app/modules/front-door/front-door.tf
app/modules/front-door/resource-group.tf
app/modules/front-door/variable.tf
app/stacks/global/back-office/data.tf
app/stacks/global/back-office/published-documents-fd.tf

Reverting code to standard to test code

---

app/components/appeals-app-services/locals.tf

https://pins-ds.atlassian.net/browse/AAPD-1195
base url to make requests to auth server

feat(appeals-fo): add auth url to frontend

---

app/modules/front-door/dns.tf
app/modules/front-door/front-door.tf

removed dns zone settings from module

---

app/components/appeals-app-services/locals.tf

feat(appeals-fo): add node_env to frontends

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl

https://pins-ds.atlassian.net/browse/AAPD-1449
Adds new feature flag to split the release of appellant dashboard from the use of sql for users

feat(appeals-fo): add sql-users flag

---

app/modules/front-door/front-door-rules.tf
app/modules/front-door/front-door.tf
app/modules/front-door/locals.tf
app/modules/front-door/monitoring.tf
app/modules/front-door/variable.tf
app/stacks/global/back-office/locals.tf
app/stacks/global/back-office/published-documents-fd.tf
app/stacks/global/back-office/variables.tf

Updated naming convention of new fd

---

app/stacks/global/back-office/published-documents-fd.tf
app/stacks/global/back-office/terragrunt.hcl
app/stacks/global/back-office/variables.tf

feat(back-office): configurable front door domain for blob

---

app/modules/front-door/front-door.tf
app/stacks/global/back-office/locals.tf
app/stacks/global/back-office/published-documents-fd.tf

fix(back-office): remove trailing slash from blob endpoint

---

app/stacks/uk-west/back-office/storage-account.tf

add allowed_origins_prod cors to prod storage account

---

app/stacks/uk-west/back-office/storage-account.tf

add missing protocol to allowed origins list for storage acc

---

app/components/back-office-app-services/applications-command-handler-functions/function-app.tf
app/components/back-office-app-services/applications-command-handler-functions/variables.tf
app/components/back-office-app-services/func-applications-command-handlers.tf

Make the blob storage custom domain available to the command handlers
Currently the command handler functions are failing to connect to the blob storage account.

Make the blob storage custom domain available to the command handlers

---

app/components/appeals-app-services/locals.tf

Makes auth url available to all apps, adds sql connection string to docs-api

feat(appeals-fo): add env vars for auth

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl

Addition of an AppealFormV2 feature flag in Appeals FO, for use whilst developing the updated appeal form.  Can be varied by LPA Code, at present only for System Test Borough
- X New feature (non-breaking change which adds functionality)

aapd-1491 add appeal form v2 feature flag

---

app/modules/front-door-premium/front-door.tf

Updated supported protocols to match with classic fd to see if premium is working similarly

---

app/stacks/global/back-office/locals.tf
app/stacks/global/back-office/terragrunt.hcl
app/stacks/global/back-office/variables.tf

Update variable name for app service primary url

---

app/stacks/global/front-door-https/terragrunt.hcl
app/stacks/global/front-door/locals.tf

Removing back office appeals frontend endpoint mappings in classic to enable the new frontend on frontdoor premium

---

app/stacks/global/back-office/terragrunt.hcl
app/stacks/global/front-door-https/terragrunt.hcl
app/stacks/global/front-door/locals.tf

Updated terraform.hcl input dependency

---

app/components/back-office-app-services/applications-command-handler-functions/function-app.tf

This seems to have been lost at some point, meaning the test-deadline-submissions function has stopped working.
* Pass SERVICE_BUS_TOPIC environment variable to command handler funcs
This seems to have been lost at some point, meaning the
test-deadline-submissions function has stopped working.
This will be followed by further changes, but this PR is needed to get the tester function working.

Pass SERVICE_BUS_TOPIC environment variable to command handler funcs

---

app/stacks/uk-west/appeals-service/monitoring.tf

feat(appeals-fo): horizon alerts earlier

---

app/stacks/uk-west/back-office/app-service.tf

Uses the new BO storage custom domain in BO WEB app settings.

fix(appeals/bo): custom domain for document storage

---

app/stacks/global/front-door/waf-policy.tf

Live issues with false positives blocking users making appeals
Ignoring csrf token and cookie value completely
Turning some common rules triggered to LOG mode in order to come up with some appropriate rule exclusions
To be revisited next week

feat(appeals-fo): reduce waf false positives

---

app/components/back-office-app-services/locals.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/secrets.tf
config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/test.hcl

Store App Config connection string in key vault and pass to services

Store App Config connection string in key vault and pass to services

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl
config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/prod.hcl
config/variables/stacks/applications-service/test.hcl
config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/test.hcl

feat: use entra groups for sql admin

---

app/stacks/uk-west/appeals-service/monitoring.tf

Alerts not firing due to window/frequency size

feat(appeals-fo): horizon failure alert frequency increase

---

app/stacks/global/front-door/waf-policy.tf

add rule override for 942400 to log instead of block

---

config/variables/stacks/applications-service/prod.hcl

Latest activated cases in BO added.
- x] My code follows the style guidelines of this project

fix(applications): Add latest BO cases

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl

fix(appeals-fo): use correct lpaCode format for feature flag

---

config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/test.hcl

Create a feature flag for the Welsh translation epic

Create a feature flag for the Welsh translation epic

---

app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/cosmosdb.tf
app/stacks/uk-west/appeals-service/locals.tf

Reduce session ttl

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/test.hcl

fix(appeals-fo): use correct lpa code for feature flag

---

app/components/back-office-app-services/locals.tf

Move App Config secret to existing_secret_refs

fix: move App Config secret to existing_secret_refs

---

config/variables/stacks/applications-service/prod.hcl

Added new cases to `back_office_integration_case_references`

feat(applications): new cases add to integration feature flag

---

app/stacks/uk-south/appeals-service/README.md
app/stacks/uk-south/appeals-service/app-service.tf
app/stacks/uk-south/appeals-service/data-appeals-bo.tf
app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/app-service.tf
app/stacks/uk-west/appeals-service/data-appeals-bo.tf

https://pins-ds.atlassian.net/browse/BOAT-1411

feat(appeals): appeal topic -> appeal-has

---

config/variables/stacks/applications-service/prod.hcl

Add additional projects to migrated list

fix(applications): Add migrated cases

---

app/stacks/global/front-door/waf-policy.tf

fix: add exceptions to the WAF rules for Welsh fields
For [APPLICS-414](https://pins-ds.atlassian.net/browse/APPLICS-414)

fix: add exceptions to the WAF rules for Welsh fields

---

app/components/back-office-app-services/applications-migration-function/function-app.tf
app/components/back-office-app-services/applications-migration-function/variables.tf
app/components/back-office-app-services/func-applications-migration.tf

add blob container domain env var to migration function

---

app/components/applications-app-services/locals.tf

The app name (and therefore URL) is different for the API in training env. The web settings need to reflect this.

fix(applications): training environment api url is shorter

---

app/components/back-office-app-services/applications-background-job-functions/function-app.tf
app/components/back-office-app-services/applications-command-handler-functions/function-app.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-455
Updates functions node version to 20.

feat(back-office): functions node 20 upgrade

---

app/modules/front-door-premium/waf-policy.tf

Implementing a custom rule for rate limit on azure front door premium

implementing waf policy on azure front door premium

---

app/components/appeals-app-services/README.md
app/components/appeals-app-services/function-app.tf
app/components/appeals-app-services/iam.tf
app/components/appeals-app-services/variables.tf
app/stacks/uk-south/appeals-service/README.md
app/stacks/uk-south/appeals-service/app-service.tf
app/stacks/uk-south/appeals-service/data-appeals-bo.tf
app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/app-service.tf
app/stacks/uk-west/appeals-service/data-appeals-bo.tf

- Adds event and service user topic subscriptions/roles
- Updates names to be clearer than current use

feat(appeals-fo): add final topic subscriptions and roles, consolidate names

---

config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/training.hcl

chore(appeals): enable integration functions in training env

---

app/components/appeals-app-services/function-app.tf
app/components/appeals-app-services/locals.tf
app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/secrets.tf

Creates a client id/secret for functions to use client creds auth to apis

feat(appeals-fo): add auth client for functions

---

app/stacks/uk-south/back-office/README.md
app/stacks/uk-south/back-office/service-bus.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/service-bus.tf

https://pins-ds.atlassian.net/browse/DEV-251
New fields required after defaults changed since AzureRM upgrade

fix(back-office): set premium_messaging_partitions for Service Bus

---

app/stacks/uk-south/applications-service/README.md
app/stacks/uk-south/applications-service/database.tf
app/stacks/uk-south/applications-service/locals.tf
app/stacks/uk-south/applications-service/secrets.tf
app/stacks/uk-south/applications-service/variables.tf

https://pins-ds.atlassian.net/browse/DEV-252
Secondary replica DBs are created automatically via the failover group.

fix(applications): remove extra secondary database

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl
config/variables/stacks/appeals-service/training.hcl

Removes a defunct feature flag (APPEAL_FORM_V2)

remove unused appeal-form-v2 flag

---

app/components/appeals-app-services/clamav.tf

fix(appeals): private dns zone is in tooling rg

---

config/variables/stacks/appeals-service/training.hcl

Set training env vars correctly

fix(appeals-fo): use set training env vars + flags

---

app/components/appeals-app-services/clamav.tf

fix(appeals): shorten clamav storage name in training env

---

app/stacks/global/front-door/README.md
app/stacks/global/front-door/waf-policy.tf

Users hitting this rule in prod (# of special chars > 12) with text area inputs

fix(appeals-fo): false positive waf block to logging mode

---

app/stacks/global/front-door/front-door.tf

Increase the timeout for frontdoor -> backend pool.

fix: increase front door timeout

---

config/variables/stacks/applications-service/training.hcl

Update training env `back_office_integration_get_applications` to `BO` as it will never need to connect to `NI`.

feat update training env vars

---

app/stacks/global/front-door/waf-policy.tf

fix(appeals-fo): remove duplicate waf rule

---

app/components/back-office-app-services/applications-background-job-functions/function-app.tf
app/components/back-office-app-services/applications-command-handler-functions/function-app.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf

This reverts commit 759948ffee50addbb4447d6b5a3e028772e8fff0.
Reverting as prod functions are still on 18 and we want to release. We will need to add this back after release.

chore: revert functions node 20 upgrade

---

app/components/appeals-app-services/README.md
app/components/appeals-app-services/function-app.tf

Provide appeal's function app access to read key vault secrets
in order to retrieve client id/secret

feature(appeals-fo): add key vault access for function app

---

app/components/networking/README.md
app/components/networking/network.tf
app/stacks/uk-south/applications-service/README.md
app/stacks/uk-south/applications-service/data.tf
app/stacks/uk-south/applications-service/redis-cache.tf
app/stacks/uk-south/applications-service/terragrunt.hcl
app/stacks/uk-south/applications-service/variables.tf
app/stacks/uk-south/back-office/README.md
app/stacks/uk-south/back-office/data.tf
app/stacks/uk-south/back-office/service-bus.tf
app/stacks/uk-south/back-office/terragrunt.hcl
app/stacks/uk-south/back-office/variables.tf
app/stacks/uk-west/applications-service/README.md
app/stacks/uk-west/applications-service/data.tf
app/stacks/uk-west/applications-service/redis-cache.tf
app/stacks/uk-west/applications-service/terragrunt.hcl
app/stacks/uk-west/applications-service/variables.tf
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/data.tf
app/stacks/uk-west/back-office/service-bus.tf
app/stacks/uk-west/back-office/synapse-private-link.tf
app/stacks/uk-west/back-office/terragrunt.hcl
app/stacks/uk-west/back-office/variables.tf

https://pins-ds.atlassian.net/browse/DEV-244
Don't create any Private DNS Zones in this repo, but use the ones from the tooling subscription instead. See ticket for more details.

fix: using tooling sub private dns zones

---

app/components/appeals-app-services/README.md
app/components/appeals-app-services/clamav.tf

feat(appeals): add clam av memory alert

---

app/components/appeals-app-services/clamav.tf

fix(appeals): fix memory usage alert units and container name filter

---

app/stacks/global/front-door/waf-policy.tf

https://pins-ds.atlassian.net/browse/AAPD-926
Makes a few more rules redirect to custom firewall error page

feat(appeals-fo): more waf rules to redirect

---

app/stacks/global/front-door/waf-policy.tf

[APPLICS 655](https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/238?selectedIssue=APPLICS-655): Change path traversal rules from block to log in firewall.
Please see the testing notes on the ticket.

fix(applications): change path traversal to log in firewall

---

README.md
app/stacks/global/front-door/waf-policy.tf

[APPLICS 741](https://pins-ds.atlassian.net/browse/APPLICS-741): Exclude firewall rules for title field

fix(applications-bo): exclude firewall rules for title field

---

app/stacks/global/front-door/waf-policy.tf

[APPLICS 655](https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/238?selectedIssue=APPLICS-655):
- Revert changing of path traversal rule action from 'Block' to 'Log' in Applications BO WAF.
- Change path traversal rule action from 'Block' to 'Log' in common WAF.

fix(applications): update rule for common waf

---

config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/test.hcl

Change to Applications project source value for Test and Development environments.  Change to 'Merge' data which will now pick up project data from both NI and BO and merge the data.  This is in line with current production config.
Check that BO cases are visible in applications all projects

task(applications): set project source to merge for non-prod envs

---

config/variables/stacks/applications-service/prod.hcl

[APPLICS 837](https://pins-ds.atlassian.net/browse/APPLICS-837): Update case refs for BACK_OFFICE_API_INTEGRATION_CASE_REFERENCES
- Added EN0110009
- Removed EN0110005

chore(applications): update back office cases

---

config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/test.hcl
config/variables/stacks/back-office/training.hcl

Create a feature flag for material changes

Create a feature flag for material changes

---

config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/test.hcl
config/variables/stacks/back-office/training.hcl

Create a feature flag for front office submissions to back office
https://pins-ds.atlassian.net/browse/APPLICS-861

feat(applications): create a feature flag for fo submissions (APPLICS-861)

---

app/stacks/global/front-door/waf-policy.tf

[Issue ticket number and link](https://pins-ds.atlassian.net/browse/APPLICS-853)
Change to include rate limit for non-uk requests of 30 in 1 minute.
This is to attempt to reduce the scraper flow that is affecting applications.
This has been deployed to test to ensure service is still operational.
- [z] New feature (non-breaking change which adds functionality)

Task/applics-853 custom rule - non uk rate limit

---

app/components/appeals-app-services/README.md
app/components/appeals-app-services/locals.tf
app/components/appeals-app-services/variables.tf
app/stacks/uk-south/appeals-service/README.md
app/stacks/uk-south/appeals-service/app-service.tf
app/stacks/uk-south/appeals-service/variables.tf
app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/app-service.tf
app/stacks/uk-west/appeals-service/variables.tf
config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl
config/variables/stacks/appeals-service/training.hcl

feat(appeals-fo): add feature flags

---

config/variables/stacks/applications-service/prod.hcl

Corrected new CBOS case reference added to back_office_integration_case_references

fix(applications): update back office case

---

config/variables/stacks/applications-service/prod.hcl

Added new CBOS case reference EN0110011 to back_office_integration_case_references.

chore(applications): add new cbos case reference

---

config/variables/stacks/applications-service/training.hcl
config/variables/stacks/back-office/training.hcl

[APPLICS 939](https://pins-ds.atlassian.net/browse/APPLICS-939): Activate bespoke folders for Training environment.

chore(cbos): applics-939 activate folders training

---

config/variables/stacks/back-office/training.hcl

Activate MC & Welsh translation feature flags in training environment
https://pins-ds.atlassian.net/browse/APPLICS-969?atlOrigin=eyJpIjoiNTczNzMwZWU0ZTczNDBiNmI2NTcwNTk3MTgxYzg2ZTMiLCJwIjoiaiJ9

feat: activate mc and welsh flags in training env

---

config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/training.hcl

[APPLICS 995](https://pins-ds.atlassian.net/browse/APPLICS-995): Activate applics-861-fo-submissions in Prod and Training
Following deployment to Training and Prod, feature should show as enabled in Azure portal:
- https://portal.azure.com/#@planninginspectorate.gov.uk/resource/subscriptions/d1d6c393-2fe3-40af-ac27-f5b6bad36735/resourceGroups/pins-rg-back-office-prod-ukw-001/providers/Microsoft.AppConfiguration/configurationStores/pins-asc-bo-prod-ukw-001/ff
- https://portal.azure.com/#@planninginspectorate.gov.uk/resource/subscriptions/dbfbfbbf-eb6f-457b-9c0c-fe3a071975bc/resourceGroups/pins-rg-back-office-training-ukw-001/providers/Microsoft.AppConfiguration/configurationStores/pins-asc-bo-training-ukw-001/ff

chore(applications): activate fo submissions

---

config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/training.hcl

Set feature flags for HAS go live

HAS go live

---

app/components/back-office-app-services/applications-migration-function/function-app.tf
app/components/back-office-app-services/locals.tf

feat: add welsh NI db secret references to migration functions

---

app/stacks/global/front-door/waf-policy.tf

https://pins-ds.atlassian.net/browse/DEV-289

feat(front-door): add ip-block WAF rule

---

app/stacks/global/front-door/waf-policy.tf

fix(front-door): re-order custom rules to avoid updating existing rule

---

app/stacks/global/front-door/waf-policy.tf

fix(front-door): add placeholder IP match

---

app/stacks/global/front-door/waf-policy.tf

Updating WAF rate limiting rules in line with MS guidance
https://pins-ds.atlassian.net/browse/DEV-97

chore(front-door): update rate limit rules in line with guidance

---

app/stacks/global/front-door/waf-policy.tf

https://pins-ds.atlassian.net/browse/DEV-289

fix(front-door): re-arrange custom rules to match the API

---

config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/test.hcl

Default training sector to true in dev and test

chore(bo): set trainig sector flag to on by default

---

app/stacks/global/front-door/waf-policy.tf

Increase rate limiting thresholds to 1500/5min to match current portal settings.

chore(waf): increase rate limiting thresholds

---

app/stacks/global/front-door-premium/.terraform.lock.hcl
app/stacks/global/front-door-premium/locals.tf
app/stacks/global/front-door-premium/main.tf
app/stacks/global/front-door-premium/terragrunt.hcl
app/stacks/global/front-door-premium/variables.tf
pipelines/infra-cd.yml

feat(front-door-premium): add shared front door instance

---

config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/training.hcl

Enable the comment planning appeals section of the appeals service

feature(appeals): enable comment planning appeal

---

config/variables/stacks/appeals-service/prod.hcl

Rollout access to V2 HAS appeals to second set of LPAs
https://pins-ds.atlassian.net/browse/A2-823

feat(appeals): second set of LPA rollouts

---

app/stacks/global/front-door/waf-policy.tf

chore/align applications FO waf policy with appeals

---

config/variables/stacks/applications-service/prod.hcl

chore(applications): add reopened registration case reference

---

app/components/appeals-app-services/function-app.tf

feat(appeals): update function app runtime to node 20

---

config/variables/stacks/applications-service/prod.hcl

- Removed case references from open_registration_case_references flag

chore(applics): remove closed registration cases

---

app/stacks/global/front-door/waf-policy.tf

Logging more SQLI rules as they keep getting hit by users with valid inputs

fix(appeals): log all sqli rules for appeals

---

.pre-commit-config.yaml
app/stacks/global/front-door-https/.terraform.lock.hcl
app/stacks/global/front-door-https/providers.tf
app/stacks/uk-south/appeals-service/.terraform.lock.hcl
app/stacks/uk-south/appeals-service/README.md
app/stacks/uk-south/appeals-service/providers.tf
app/stacks/uk-south/applications-service/.terraform.lock.hcl
app/stacks/uk-south/applications-service/README.md
app/stacks/uk-south/applications-service/providers.tf
app/stacks/uk-south/back-office/.terraform.lock.hcl
app/stacks/uk-south/back-office/README.md
app/stacks/uk-south/back-office/providers.tf
app/stacks/uk-south/common/.terraform.lock.hcl
app/stacks/uk-south/common/README.md
app/stacks/uk-south/common/providers.tf
app/stacks/uk-west/appeals-service/.terraform.lock.hcl
app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/providers.tf
app/stacks/uk-west/applications-service/.terraform.lock.hcl
app/stacks/uk-west/applications-service/README.md
app/stacks/uk-west/applications-service/providers.tf
app/stacks/uk-west/back-office/.terraform.lock.hcl
app/stacks/uk-west/back-office/README.md
app/stacks/uk-west/back-office/providers.tf
app/stacks/uk-west/common/.terraform.lock.hcl
app/stacks/uk-west/common/README.md
app/stacks/uk-west/common/providers.tf
config/providers.tf

upgrading-terraform

---

config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/test.hcl
config/variables/stacks/back-office/training.hcl

[APPLICS-1227](https://pins-ds.atlassian.net/browse/APPLICS-1227): Remove feature flag for Material Changes
[APPLICS-978]: https://pins-ds.atlassian.net/browse/APPLICS-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPLICS-1227]: https://pins-ds.atlassian.net/browse/APPLICS-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(applic-bo): remove material change flag

---

app/stacks/global/front-door/.terraform.lock.hcl
app/stacks/global/front-door/waf-policy.tf

APPLICS-1237
Change the behaviour of SQLi triggers to log only for CBOS.
Updates Terraform code to match changes already made manually in the Azure Portal
- [n/a] My Tech Lead is aware of any infrastructure changes that will cost money

chore(front-door): change sqli rules to log only

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl
config/variables/stacks/appeals-service/training.hcl

feat(appeals): use 2nd test lpa for v2 testing

---

app/components/appeals-app-services/app-service.tf
app/components/appeals-app-services/locals.tf

https://pins-ds.atlassian.net/browse/A2-1944
Uses new public_network_access setting to ensure staging slots have the same networking rules set as the prod slot

fix(appeals): set staging slot access

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl
config/variables/stacks/appeals-service/training.hcl

fix(appeals): use lpa targetting for questionnaire

---

app/components/appeals-app-services/locals.tf

https://pins-ds.atlassian.net/browse/A2-2055
adds env var for representation submission topic

add representation submission topic env var

---

app/components/appeals-app-services/app-service.tf

With infrastructure module v1.38, all site_config changes were ignored due to a incorrect ignore_changes entry. This has been updated to only ignore  the docker image name/tag.
This ensures IP restrictions allowing only front_door and default action settings will apply.
https://pins-ds.atlassian.net/browse/DEV-308
https://pins-ds.atlassian.net/browse/DEV-351

fix(infrastructure): updating module version to 1.38 for Appeals App Service

---

config/variables/stacks/applications-service/prod.hcl

https://pins-ds.atlassian.net/browse/APPLICS-1289
Latest Prod case redirect list:
EN010152,WW010002,EN020023,TR050008,EN010126,EN020025,EN010157,TR040010, TR010033,EN010111,EN060006,TR040012,TR050003,WA010002,TR030005,TR020004,EN010102

chore(applications):applics-1289 add new redirect case refs

---

app/components/appeals-app-services/locals.tf

Adds private endpoint to front end public app
Allows pipeline to reach the staging slot which was previously blocked by applying the access restrictions (restricted from front door only)

fix(appeals): enable PE on appeals front-end

---

app/components/back-office-app-services/app-service.tf
app/components/back-office-app-services/locals.tf

With infrastructure module v1.38, 
- Uses new public_network_access setting to ensure staging slots have the same networking rules set as the prod slot
- Deny all public network access for Api's
- Allow only front door access for Web Apps
- All site_config changes were ignored due to a incorrect ignore_changes entry. This has been updated to only ignore  the docker image name/tag.
https://pins-ds.atlassian.net/browse/DEV-308
https://pins-ds.atlassian.net/browse/DEV-351

fix(infrastructure): updating module version to 1.38 for Back Office

---

app/components/appeals-app-services/iam.tf

Add role for FO appeal-representation service bus subscription

add appeal representation subscription role

---

config/variables/stacks/applications-service/prod.hcl

chore(applications): add migration case references

---

app/components/appeals-app-services/iam.tf

Amend the IAM role for sending representations to service bus topic

fix fo representation submission role

---

app/stacks/global/front-door-https/terragrunt.hcl
config/variables/stacks/front-door-https/dev.hcl
config/variables/stacks/front-door-https/prod.hcl
config/variables/stacks/front-door-https/test.hcl
config/variables/stacks/front-door-https/training.hcl

~~Merge this once comment app removed from prod~~
Removes final comment planning appeal code

fix: revert temp changes for removing comment app

---

app/components/appeals-app-services/app-service.tf
app/components/appeals-app-services/function-app.tf
app/components/applications-app-services/app-service.tf
app/components/applications-app-services/function-app.tf
app/components/back-office-app-services/app-service.tf
app/components/back-office-app-services/applications-background-job-functions/function-app.tf
app/components/back-office-app-services/applications-command-handler-functions/function-app.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf

chore(tooling): updating module call

---

app/components/applications-app-services/locals.tf
app/components/applications-app-services/variables.tf
app/stacks/uk-south/applications-service/.terraform.lock.hcl
app/stacks/uk-south/applications-service/app-service.tf
app/stacks/uk-south/applications-service/variables.tf
app/stacks/uk-west/applications-service/.terraform.lock.hcl
app/stacks/uk-west/applications-service/app-service.tf
app/stacks/uk-west/applications-service/variables.tf
config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/prod.hcl
config/variables/stacks/applications-service/test.hcl
config/variables/stacks/applications-service/training.hcl

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1323
Feature flag to enable / disable Welsh cases in FO (project-search, register-of-applications, and CSV download)

feat: allowWelshCases featureflag

---

app/stacks/global/front-door/waf-policy.tf

https://pins-ds.atlassian.net/browse/APPLICS-1278

chore(applicatinos): set additional waf rules to log

---

app/components/applications-app-services/locals.tf

fix: don't restrict applications fo API to front door

---

app/components/appeals-app-services/app-service.tf
app/components/appeals-app-services/data-tooling.tf
app/components/appeals-app-services/locals.tf
app/components/appeals-app-services/variables.tf
app/stacks/uk-south/appeals-service/app-service.tf
app/stacks/uk-south/appeals-service/variables.tf
app/stacks/uk-west/appeals-service/app-service.tf
app/stacks/uk-west/appeals-service/variables.tf
config/variables/dev.hcl
config/variables/prod.hcl
config/variables/test.hcl
config/variables/training.hcl

- Adding Authentication to Dev/Test/Training environment to ensure only users with PINS Id can access the project
- For Prod, authentication is set as 'false'
- Terraform code changes are added to both 'uk-south' and 'uk-west' regions
**Ticket for easy authentication link:** https://pins-ds.atlassian.net/browse/DEV-323
**Ticket Number:** DEV-323
- Infrastructure module reference for app service should be 1.37 or later to include this change
- Adding azurerm_client_config in data.tf to retrieve tenant ID
Infra-CD plan for Dev, Test and training environment: 
branch= task/authentication stack=appeals-service and region=uk-west
https://dev.azure.com/planninginspectorate/infrastructure/_build/results?buildId=103171&view=logs&s=e8750460-45fe-5a2d-8bf3-d4f3cb4069a0
- [x ] New feature …

feat(infrastructure): adding authentication configurations for appeals 

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/test.hcl

adds new dev and test env template ids for s78 appeal submitted email to lpa
used the [prod](https://www.notifications.service.gov.uk/services/57ab0834-106d-438c-b0b9-3c8f2c268738/templates/3621ad01-9599-422e-b15c-903725261e6f) template for the [new template](https://www.notifications.service.gov.uk/services/c46d894e-d10e-4c46-a467-019576cd906a/templates/6e513a04-c06a-434a-b517-b733fa2c73e3)

use new template id for appeal submitted lpa email

---

config/variables/dev.hcl
config/variables/prod.hcl
config/variables/test.hcl
config/variables/training.hcl

Updating value for allowed application for appeals 
Updating service principle id of appeals planning decision which is used to run git verify pipeline

fix(infrastructure): updating application id for appeals authentication

---

app/components/applications-app-services/app-service.tf
app/components/applications-app-services/function-app.tf
app/components/applications-app-services/locals.tf
app/components/applications-app-services/variables.tf
app/stacks/uk-south/applications-service/app-service.tf
app/stacks/uk-west/applications-service/app-service-plan.tf
app/stacks/uk-west/applications-service/app-service.tf
app/stacks/uk-west/applications-service/variables.tf
config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/prod.hcl
config/variables/stacks/applications-service/test.hcl
config/variables/stacks/applications-service/training.hcl

- setup a new app service plan
- set session affinity

feat: scale applications front office in prod

---

config/variables/test.hcl
config/variables/training.hcl

Temp revert easy auth as due to pdf generation

fix(appeals): temp revert auth for test+training

---

app/components/back-office-app-services/iam.tf

APPLICS-1404
Gives Back Office API write permission to the document uploads Blob storage container in order to allow uploading migrated HTML files

feat: grant back office api permission to write to blob

---

app/components/appeals-app-services/function-app.tf

https://pins-ds.atlassian.net/browse/A2-1926
related appeals PR: https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/4196

feat(appeals): bump node version for function app

---

config/variables/test.hcl
config/variables/training.hcl

This reverts commit 2279b641138d449761f15913ff0641ef923ca99f.
- Code issue resolved so reinstating easy auth in test/training

Revert "fix(appeals): temp revert auth for test+training"

---

app/stacks/uk-south/common/variables.tf
app/stacks/uk-west/common/variables.tf

Only 1 function app, can be scaled down

feat(appeals): scale down function app

---

app/components/appeals-app-services/README.md
app/components/appeals-app-services/locals.tf
app/components/appeals-app-services/variables.tf
app/stacks/uk-south/appeals-service/README.md
app/stacks/uk-south/appeals-service/app-service.tf
app/stacks/uk-south/appeals-service/variables.tf
app/stacks/uk-west/appeals-service/README.md
app/stacks/uk-west/appeals-service/app-service.tf
app/stacks/uk-west/appeals-service/variables.tf
config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl
config/variables/stacks/appeals-service/training.hcl

https://pins-ds.atlassian.net/browse/A2-2872
Adds a new generic notify template id

feat(appeals): add generic notify template

---

app/components/applications-app-services/locals.tf
app/components/applications-app-services/variables.tf
app/stacks/uk-south/applications-service/app-service.tf
app/stacks/uk-south/applications-service/variables.tf
app/stacks/uk-west/applications-service/app-service.tf
app/stacks/uk-west/applications-service/variables.tf
config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/prod.hcl
config/variables/stacks/applications-service/test.hcl
config/variables/stacks/applications-service/training.hcl

[APPLICS-1494](https://pins-ds.atlassian.net/browse/APPLICS-1494): Create new feature flags for Register of Advice page
Created an API feature flag and web front end feature flag to hide the changes that will be made to the Register of Advice page until after migration has been completed.
[APPLICS-1494]: https://pins-ds.atlassian.net/browse/APPLICS-1494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(applications): create register of advice feature flags (applics-1494)

---

app/components/applications-app-services/function-app.tf

https://pins-ds.atlassian.net/browse/APPLICS-1234
Bump function app node version to 20

chore(applications): bump functions app to node 20

---

app/stacks/global/front-door-premium/main.tf

Adding Log analytics and diagnostic setting to premium front door
[Task](https://pins-ds.atlassian.net/browse/DEV-320)
[Terragrunt plan for PROD](https://dev.azure.com/planninginspectorate/infrastructure/_build/results?buildId=112665&view=logs&j=5d9f05ff-3709-55e7-4664-c78594c015f3&t=a074613e-dc62-53d4-6bad-f7700b707df8&l=52)

feat(infrastructure): adding log analytics and diagnostic settings to premium frontdoor

---

config/variables/training.hcl

Training pipeline has different identity

fix(appeals): allow training pipeline to auth

---

app/components/appeals-app-services/clamav.tf
app/components/appeals-app-services/variables.tf
app/stacks/uk-south/appeals-service/app-service.tf
app/stacks/uk-south/appeals-service/variables.tf
app/stacks/uk-west/appeals-service/app-service.tf
app/stacks/uk-west/appeals-service/variables.tf

fix(appeals): fix script for updating clam IP on private DNS zone

---

app/components/applications-app-services/locals.tf

Updating endpoint subnet id as it was set to null, with this change it is set to endpoint subnet id only for application front office wfe.  No changes made to backend api
Also setting inbound connectivity as true for application service frontend

fix(infrastructure): updating endpoint subnet id for applications front office

---

config/variables/stacks/applications-service/test.hcl
config/variables/stacks/applications-service/training.hcl
config/variables/stacks/back-office/test.hcl
config/variables/stacks/back-office/training.hcl

https://pins-ds.atlassian.net/browse/DEV-465
test and training SQL databases are under utilised.

reduce test and training SQL tiers to S0/250GB

---

config/variables/stacks/appeals-service/dev.hcl
config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/test.hcl
config/variables/stacks/appeals-service/training.hcl

Adds feature flags for CAS and Adverts

feat(appeals): add cas/adverts feature flags

---

pipelines/infra-cd.yml
pipelines/infra-ci-plan.yml
pipelines/infra-ci.yml

fix: updating pipeline tags to common pipelines

---

app/components/appeals-app-services/clamav.tf
app/components/appeals-app-services/variables.tf
app/stacks/uk-south/appeals-service/app-service.tf
app/stacks/uk-south/appeals-service/monitoring.tf
app/stacks/uk-west/appeals-service/app-service.tf
app/stacks/uk-west/appeals-service/monitoring.tf

- Connect ClamAV container group to monitor instance to keep logs after crash/restart
- Bump GB as we see spikes before crash
- Added a max GB to logs to limit costs, if this causes a massive increase in logging
- Pin ClamAV container image to 1.4 LTS to avoid any issues with potential breaking changes, leaving patch version free as this will include CVE fixes

ClamAV issues

---

app/components/appeals-app-services/app-service.tf
app/components/appeals-app-services/function-app.tf
app/components/applications-app-services/app-service.tf
app/components/applications-app-services/function-app.tf
app/components/back-office-app-services/app-service.tf
app/components/back-office-app-services/applications-background-job-functions/function-app.tf
app/components/back-office-app-services/applications-command-handler-functions/function-app.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf
app/stacks/global/front-door-https/providers.tf
app/stacks/uk-south/appeals-service/providers.tf
app/stacks/uk-south/applications-service/providers.tf
app/stacks/uk-south/back-office/providers.tf
app/stacks/uk-south/common/providers.tf
app/stacks/uk-west/appeals-service/providers.tf
app/stacks/uk-west/applications-service/providers.tf
app/stacks/uk-west/back-office/providers.tf
app/stacks/uk-west/common/providers.tf

https://pins-ds.atlassian.net/browse/DEV-467

chore: support terraform 1.12

---

config/variables/stacks/appeals-service/prod.hcl

feat(appeals): LPA rollout

---

config/variables/stacks/appeals-service/prod.hcl

This reverts commit a5a94fe536c721c36f13f8b74974347c572eeb49.
Delay to rollout from business

Revert "feat(appeals): lpa rollout"

---

config/variables/stacks/appeals-service/prod.hcl
config/variables/stacks/appeals-service/training.hcl

Enabling scoping opinion as it is feature complete

feat(appeals): enable scoping opinion

---

app/components/appeals-app-services/app-service.tf
app/components/appeals-app-services/function-app.tf
app/components/applications-app-services/app-service.tf
app/components/applications-app-services/function-app.tf
app/components/back-office-app-services/app-service.tf
app/components/back-office-app-services/applications-background-job-functions/function-app.tf
app/components/back-office-app-services/applications-command-handler-functions/function-app.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf

Ensure staging slots get the same settings as the default, for worker_count and client affinity.
https://pins-ds.atlassian.net/browse/DEV-479

fix: update modules ref to 1.49, fixing staging slot issues (worker_count and client_affinity)

---

app/components/appeals-app-services/function-app.tf
app/components/appeals-app-services/iam.tf
app/components/appeals-app-services/variables.tf
app/stacks/uk-south/appeals-service/app-service.tf
app/stacks/uk-south/appeals-service/data-appeals-bo.tf
app/stacks/uk-west/appeals-service/app-service.tf
app/stacks/uk-west/appeals-service/data-appeals-bo.tf

Appeals event estimate topic subscription and permissions

feat(appeals): add event estimate subscription

---

config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/test.hcl

Adding variable in dev and test .hcl files as pipeline is failing with missing attribute error

fix(infrastructure): adding monitoring_alerts_enabled variable for dev and test

---

app/stacks/uk-west/back-office/monitoring.tf

feat(infrastructure): creating metrics for storage account back office

---

app/stacks/uk-west/back-office/monitoring.tf

changing value to target the blob not the storage account

---

app/components/back-office-app-services/iam.tf
app/components/back-office-app-services/locals.tf
app/components/back-office-app-services/variables.tf
app/components/networking/network.tf
app/stacks/uk-west/back-office/app-service.tf
app/stacks/uk-west/back-office/data.tf
app/stacks/uk-west/back-office/text-analytics.tf
app/stacks/uk-west/back-office/variables.tf
config/variables/stacks/back-office/dev.hcl
config/variables/stacks/back-office/prod.hcl
config/variables/stacks/back-office/test.hcl
config/variables/stacks/back-office/training.hcl

Infra work for https://github.com/Planning-Inspectorate/back-office/pull/2894

feat(back-office): configure Azure language service

---

config/variables/stacks/applications-service/dev.hcl
config/variables/stacks/applications-service/prod.hcl
config/variables/stacks/applications-service/test.hcl
config/variables/stacks/applications-service/training.hcl

Set the `FEATURE_ALLOW_WELSH_CASES` to true as the functionality is now live.

feat(applications): set FEATURE_ALLOW_WELSH_CASES to true in all envs

---

app/components/applications-app-services/function-app.tf

https://pins-ds.atlassian.net/browse/APPLICS-1692
Add BO representation unpublish subscriber
linked to https://github.com/Planning-Inspectorate/applications-service/pull/1504

feat(applications): add applications-nsip-representation-unpublish BO subscriber

---

app/stacks/uk-west/back-office/locals.tf

Set Prisma connection limit to 10 in CBOS prod

feat(back-office): set Prisma connection limit to 10

---

config/variables/stacks/back-office/test.hcl

chore(cbos): add case to ai redaction in test

---

app/components/appeals-app-services/function-app.tf
app/components/applications-app-services/function-app.tf
app/components/back-office-app-services/applications-background-job-functions/function-app.tf
app/components/back-office-app-services/applications-command-handler-functions/function-app.tf
app/components/back-office-app-services/applications-migration-function/function-app.tf

https://pins-ds.atlassian.net/browse/DEV-547

fix: update node-function-app#1.50 to reduce excessive logging

---

config/variables/stacks/back-office/prod.hcl

chore(applications): add sensitive case ref to a flag

---

app/components/networking/vpn-gateway.tf

As IPs are migrated over portal, this PR includes the terraform configuration update to reflect the changes in IaC
Ticket: https://pins-ds.atlassian.net/browse/DEV-508
UK-West location and common stack 
CD- PLAN for all ENV: https://dev.azure.com/planninginspectorate/infrastructure/_build/results?buildId=135316&view=results

fix(network): updating standard SKU and static allocation for public IPs

---

app/components/back-office-app-services/locals.tf

Updating the Boolean value to create private endpoints for back office 
Part of [ticket](https://pins-ds.atlassian.net/browse/DEV-519) to update deploy pipeline

fix(network): adding private endpoints for back office

---

app/stacks/uk-west/applications-service/monitoring.tf
app/stacks/uk-west/applications-service/vpn-gateway.tf

chore(infrastructure): creating moved blocks for training resources
